### ISSUE TITLE
Support declarative setters for subpackages

### ISSUE THREAD

**Issue by yhrn** [GoogleContainerTools/kpt#1051]
We are looking at the new package composition functionality and for it to be truly useful for us we would need to be able to declare setter values for dependencies in the dependent package.

## Use case

We provide event delivery infrastructure for the entire company. 

We have one repository where internal customers define their event types, including some options that affect how we need to configure our infrastructure. The event definitions are currently in a completely prorietary YAML format but it would be close to trivial to turn them into KRM via a simple Kpt source function.

For each event type we need to spin up some infrastructure, declared as KRM (Config Connector resources, e.g. Pub/Sub topics/subscriptions, Dataflow jobs, GCS buckets, etc.), in a separate repository/Kpt package. In reality we have multiple such repos/packages for different parts of our infrastructure but they are managed independently so it's just multiple instances of the same use case.

When there are changes to the event definitions or infrastructure repos our CD process will render one infrastructure package per event type, setting some different values based on the event definition then expose this as composite package that can be deployed. We (the infra team) also need to be able to specify some additional setter values for specific event types, e.g. because we need to tweak some aspects for high volume event types or because we are dealing with an incident. So we would like to be able to have something like this that we would update on each change:

```yaml
apiVersion: kpt.dev/v1alpha1
kind: Kptfile
metadata:
  name: composite-infra-package
  annotations:
    config.kubernetes.io/function: |
      starlark:
        path: update-comp-package.star
        name: update-comp-package
packageMetadata:
  shortDescription: A composite package with all the event infra
dependencies:
- name: some-event
  updateStrategy: fast-forward
  git:
    directory: /packages/per-event-infra
    ref: master
    repo: https://repos.net/events/some-infra
  setters:
  # Derived from event definition
  - name: event-name
    value: some-event
  # Derived from event definition
  - name: priority
    value: normal
- name: high-volume-event
  updateStrategy: fast-forward
  git:
    directory: /packages/per-event-infra
    ref: master
    repo: https://repos.net/events/some-infra
  setters:
  - name: event-name
    value: high-volume-event
  - name: priority
    value: high
  # Manually added tweak
  - name: machine-type
    value: n2-highmem-8
```

Note that this is just to exemplify what we want to do rather than a suggestion design. Another aspect of this example is that updating the Kptfile via a declarative `kpt fn run` wouldn't work as Kptfiles are excluded in this context.

We would also like to be able to create similar packages for test and dev scenarios but then we would just set it up manually for a small, fixed set of event types with some different configuration (setter values). So we need the same functionality there but we wouldn't dynamically update the composite package definition.
