### ISSUE TITLE
Support setter values referencing other setters

### ISSUE THREAD

**Issue by yhrn** [GoogleContainerTools/kpt#1106]
This relates to #1051 and the proposed design referenced there, i.e. it assumes that there is a "setter values configuration section" where values for setters can be specified declaratively. In that scenario it would be useful if setters could be referenced from other setter values, e.g.:

```yaml
setterValues:
  setter-1: ${setter-2}-something-${setter-3}
  my-subpackage-dir:
    subpackage-setter: ${setter-1}
```

Use cases:

1. The most important use case imo would be to be able to expose subpackage configuration knobs as part of the parent composite package interface. To make this work it would be enough to support referencing parent setters from subpackage setter values.
1. Alleviate the duplication drawback of repeated patterns if substitutions are removed. For this to work it must be possible reference setters in the same package.

The corresponding functionality still doesn't exist in Helm (referencing values from values) and it was one of the absolute worst pain points I experienced when working with it.
