### ISSUE TITLE
kpt pkg get single files

### ISSUE THREAD

**Issue by yanniszark** [GoogleContainerTools/kpt#1326]
### Problem

Certain projects distribute installation manifests as YAML files in release artifacts.
For example: https://github.com/knative/serving/releases/v0.19.0

I would like to still take advantage of `kpt pkg get` in order to track the upstream source.

**Comment by mikebz** [comment]
@yanniszark let me ask you a few questions:

1) are these files stored in some directory in a git repo?  I looked a round a bit but didn't find an obvious location where they are all located.
2) are you looking to change those files or file contents somehow or just deploy all of them together?

Thanks!

**Comment by yanniszark** [comment]
> are these files stored in some directory in a git repo? I looked a round a bit but didn't find an obvious location where they are all located.

The YAML installation files are included in the release downloads. AFAIK, releases are a GitHub thing, based on git tags, where GitHub lets you attach downloads. The final YAMLs are generated with a script: https://github.com/knative/serving/blob/master/hack/generate-yamls.sh
https://github.com/knative/serving/tree/master/config

> are you looking to change those files or file contents somehow or just deploy all of them together?

I want to use those files and possibly make my own customizations on top (e.g., with kustomize). I could download them and use them. But that doesn't give me the ability to:
- Track their origin (which the `Kptfile` does).
- (optionally) Perform clever merges which `kpt` provides.

Instead of devising another format to track them, I was wondering if `kpt`/`Kptfile` would support such a use-case.

**Comment by mikebz** [comment]
Thank you for the context.  Under the hood kpt uses git to grab files.  I haven't seen a way to use the git interface to get files from a release.  if you have found a way we can see how to use that.  So if there was a way get the artifacts that you are looking for from the command line using git binary - that's a small delta to what we currently support.

The alternative is to grab the relevant directories directly as Kpt packages.  For instance some of them are here:
https://github.com/knative/serving/config/post-install

Kpt does support branches and tags so if you find the sources for all the files you care about you can grab the directories for them.  Keep in mind that currently we grab the entire directory.

Example:
```
> kpt pkg get https://github.com/knative/serving/config/post-install .
fetching package config/post-install from https://github.com/knative/serving to post-install
```

You might already be aware that the source doesn't need to have a Kptfile to be a kpt package.  We create one on the fly.  For this particular operation Kptfile is this:
```
apiVersion: kpt.dev/v1alpha1                                                                                                              
kind: Kptfile                                                                                                                             
metadata:                                                                                                                                 
  name: post-install                                                                                                                      
upstream:                                                                                                                                 
  type: git                                                                                                                               
  git:                                                                                                                                    
    commit: edf5ae036c246b98b4392017fb1d94b7ced066b0                                                                                      
    repo: https://github.com/knative/serving                                                                                              
    directory: config/post-install                                                                                                        
    ref: master                                                                                                                           
               
```
You can then do all the fun things with that like `kpt pkg update` to get the latest.

Some of the files config files are intermixed with go files but I don't think it matters for the purposes of `apply`.
