### ISSUE TITLE
Feature Request: kpt cfg generate-substrs

### ISSUE THREAD

**Issue by karlkfi** [GoogleContainerTools/kpt#1375]
A coworker wrote a script that takes key value pairs, finds all YAML values that contain those values, and generates kpt substitutions for them. I was hoping something similar could be added to kpt to generate substrs based on setter values already in the Kptfile.

http://go/kpt-cfg-gen (Google internal gist)

Examples of substrs generated:
```
    io.k8s.cli.substitutions._subst-1:
      x-k8s-cli:
        substitution:
          name: _subst-1
          pattern: kcc-${tenant-project-id}
          values:
          - marker: ${tenant-project-id}
            ref: '#/definitions/io.k8s.cli.setters.tenant-project-id'
```

```
    io.k8s.cli.substitutions._subst-8:
      x-k8s-cli:
        substitution:
          name: _subst-8
          pattern: ${_subst-1}@${admin-project-id}.iam.gserviceaccount.com
          values:
          - marker: ${_subst-1}
            ref: '#/definitions/io.k8s.cli.substitutions._subst-1'
          - marker: ${admin-project-id}
            ref: '#/definitions/io.k8s.cli.setters.admin-project-id'
    io.k8s.cli.substitutions._subst-9:
      x-k8s-cli:
        substitution:
          name: _subst-9
          pattern: serviceAccount:${_subst-8}
          values:
          - marker: ${_subst-8}
            ref: '#/definitions/io.k8s.cli.substitutions._subst-8'
```

**Comment by frankfarzan** [comment]
@phanimarupaka

Setters are being redesigned to eliminate need for explicit substitutions. You can create setter references (with interpolation) either manually (adding the comment) or in bulk by using search and replace.

For example:

1.  Create a setter for a GCP project ID:

`$ kpt cfg create-setter DIR/ project-id --description "GCP Project ID" --required`


Assume there are two fields across config files with value "project-id-foo” and “project-id-bar”:
```
project-id-foo
...
project-id-bar
```
And you have setter `project-id` set to value `lazy-koala`

2. Create setter references (interpolations) across configs:

`$ kpt cfg search DIR/ --by-value-regex “project-id-(.*)” --put-pattern “my-${project-id}-${1}”`

Final results:

```
my-lazy-koala-foo # my-${project-id}-foo
...
my-lazy-koala-bar # my-${project-id}-bar
```

**Comment by karlkfi** [comment]
What I'm suggesting would be even easier to use and less typing.

Instead of a human having to decide what the pattern should be for each substitution, kpt-cfg-gen finds all substring matches of setter values and automatically generates the substrs.

I've used it to generate 20 substrs at a time with a single command. Then I just manually reviewed the changes to make sure I like them before committing.

I'm proposing something similar. You'd just run `kpt cfg generate-substrs` and it would use the values of the setters you already created to find all YAML values that should be substrs and generate the interpolation automatically.

**Comment by mikebz** [comment]
@frankfarzan I am curious about your philosophical designation for setters.  Are they supposed to be top level package parameters and the hydration is based on them or are they a shortcut for simple mutations (set value, replace, etc.)

**Comment by phanimarupaka** [comment]
@karlkfi This seems to be an interesting use-case. So you build the base setter definitions and want to delegate the work to kpt in order to figure out building the patterns for all the fields ? What if there is a value whose substring matches a setter but you don't want to parameterize it ? You will have to manually delete that substitution/pattern correct ? I am not sure how common is this use-case to be baked into kpt cli. 

On a side note actual value of _subst_9 must be huge here correct ? Currently you are leveraging [nested substitutions](https://googlecontainertools.github.io/kpt/guides/producer/substitutions/#nested-substitutions) here but that will go away with new design and you have to elaborate the pattern with all setters similar to terraform. The new pattern comment would look like
# serviceAccount:$kcc-${tenant-project-id}@${admin-project-id}.iam.gserviceaccount.com

**Comment by frankfarzan** [comment]
@karlkfi I think that script is equivalent to (and can be provided as porcelain for):

$ kpt cfg search DIR/ --by-value-regex “(.*)project-id(.*)” --put-pattern “{$1}${project-id}${2}”

Note that there's little value in having substitutions defined as first class citizens in the Kptfile.

@mikebz: That's a bigger design discussion we should track elsewhere.

**Comment by phanimarupaka** [comment]
@frankfarzan I think the script does more that just that. The command you mentioned only adds pattern to regex value that match (.*)some-value(.*). But the script parameterizes all the fields values with substring match with any of the setter values. @karlkfi Correct me if I am wrong.

**Comment by karlkfi** [comment]
re: @phanimarupaka

> So you build the base setter definitions and want to delegate the work to kpt in order to figure out building the patterns for all the fields ? 

Yes

> What if there is a value whose substring matches a setter but you don't want to parameterize it ? You will have to manually delete that substitution/pattern correct ? 

Yes. This is less work than creating it manually. And if the result is a big mess you can always git revert and do it manually. Or revert, comment out the line you want ignored, run the generator again, and un-comment the preserved line.

> I am not sure how common is this use-case to be baked into kpt cli.

I've written 9 kpt packages for my current project and used the sustr generator on 7 of them. The others didn't have any substitutions and only contained one file other than the kptfile.

> On a side note actual value of _subst_9 must be huge here correct ? Currently you are leveraging nested substitutions here but that will go away with new design and you have to elaborate the pattern with all setters similar to terraform. The new pattern comment would look like serviceAccount:$kcc-${tenant-project-id}@${admin-project-id}.iam.gserviceaccount.com

Correct. If you get rid of named substitutions they can't be re-used in other substitutions. 

re: @frankfarzan

> Note that there's little value in having substitutions defined as first class citizens in the Kptfile.

The value is:
1. being about to use the named substr multiple times without defining the pattern multiple times.
2. being able to use the named substr in other substrs without repeating yourself


I suggest kpt should support both the new inline anonymous substitutions and the current named substitutions. Named substitutions also allow using the same pattern in multiple places without having to re-define the pattern everywhere. 

I also suggest merging named substitutions into setters, so that the substitution is just the default value of the setter. That way they can be both re-used and overridden with kpt cfg set.

For example:
```
openAPI:
  definitions:
    io.k8s.cli.setters.project-id:
      x-k8s-cli:
        setter:
          name: project-id
          default: ${tenant}-${environ}-${org}-${project-id-random-suffix}
```

> I think that script is equivalent to (and can be provided as porcelain for)...

As @phanimarupaka mentioned, the generator script isn't just porcelain. It finds matches and generates the patterns for all substrs at the same time using all pre-defined setters. It's much less typing AND much less thinking, because the user dosn't even need to know what or where the substrs should be. The command does all that manual labor itself and the user just reviews the changes to make sure it made good choices.

**Comment by karlkfi** [comment]
On a related note, if you merge substr patterns into setters as default values, then you should automatically get the ability for substrs to be inherited into sub-packages as setters. This was another feature I was going to request, but I think merging setters and substrs is a better plan.

This would allow for re-use of named substitutions not just in the same package but in sub-packages. The sub-package could then mark the setter as required while in the parent package it's optional and defaults to the value of the substitution.

**Comment by phanimarupaka** [comment]
The default would actually be the value(similar to terraform default) and not the pattern. The pattern will be added as a comment to the field itself in the resource configs. 

I am not sure I followed the subpackages part though. Can you elaborate with an example ?

**Comment by karlkfi** [comment]
> The default would actually be the value(similar to terraform default) and not the pattern. The pattern will be added as a comment to the field itself in the resource configs.

I assume you mean this will be true with the new inline substitution syntax. 

But what I'm suggesting is a default pattern, not a default value, and for a named setter/substr in the kptfile, not an inline substr. This would allow the value to be overridden by the user using `kpt pkg set`, but otherwise it would default to the substitution resulting from the pattern that depends on other setters.

I guess an alternate option (if you don't keep named substrs in the kptfile) would be to allow inline substitutions to be overridden by `kpt pkg set`, but that would then require storing the set value in the kptfile, in order to preserve it during inheritance and updating.

**Comment by karlkfi** [comment]
Package Example:
```
openAPI:
  definitions:
    io.k8s.cli.setters.project-id:
      x-k8s-cli:
        setter:
          name: project-id
          default: ${tenant}-${environ}-${org}-${project-id-random-suffix}
```

Sub-Package Example:
```
openAPI:
  definitions:
    io.k8s.cli.setters.project-id:
      x-k8s-cli:
        setter:
          name: project-id
          required: true
```

With this, the pattern only needs to exist in the parent package kptfile and can be used in parent package and the sub-package. And if the user decides to `kpt cfg set . project-id <value>` they could override the value at the parent package and have it inherited into the sub-package. OR they could set project-id on the sub-package and have them be different.

**Comment by frankfarzan** [comment]
@karlkfi Supporting explicit subs in addition to inline interpolation is not an unreasonable FR if they're referenced in many places. Here's an example use case where explicit setters is adding noise and inline interpolation makes more sense:

https://github.com/GoogleCloudPlatform/solutions-modern-cicd-anthos/blob/krm/krm/cicd_gitlab/Kptfile

We will incorporate this suggestion in new setter design.

**Comment by karlkfi** [comment]
I've extracted the request to merge setters and substrs to its own issue to keep this one focused on the substr generation. But they are closely related. 

https://github.com/GoogleContainerTools/kpt/issues/1383

**Comment by karlkfi** [comment]
I think this FR is probably still valid with kpt v1 syntax. It just needs some tweaking.

Basically with kpt v1 there's no more index of setters in the kptfile, so any script to do the substitution generation would need to read the entire set of resources, parse the inline comments, and extract a list of setters and their current values... I hope kpt already has a library function for this.

Hypothetically this could be done by reading the pipeline steps, finding the apply-setters step, and extracting the keys and values from the inputs, but that assumes that the kptfiles is a complete list and matches the keys and values in the resources themselves...

After somehow extracting a complete list of setter keys and values, the substitution generator could then do the same thing the code I shared does: find values that contain the setter values as substrings and generate substitutions for the, except just by applying a comment, since no kptfile changes will be needed (assuming the kptfile already has an apply-setters step with the right inputs for the setters).

**Comment by phanimarupaka** [comment]
@karlkfi Yes. This functionality a variant of apply-setters function and can be achieved with some tweaking to it as you mentioned. This qualifies to be a separate function. 

I think the question here is, who should write and maintain this function and what should be the timeline? So this is more of a planning question which I would redirect to @mikebz @frankfarzan

**Comment by karlkfi** [comment]
Hmm, you're right. Since it no longer needs to modify the kptfile or make kpt cli calls it could be a kpt function. All it has to do is add kpt-set inline comments. I hadn't thought of that. That means anyone could write it.

**Comment by mikebz** [comment]
@karlkfi I want to make sure we addressed the scenario.  If I can summarize what I read previously is that you'd like to replace many locations with one setter value at once.   I believe this is addressed here: https://catalog.kpt.dev/search-replace/v0.1/ but maybe not completely.  Happy to re-engage.

**Comment by phanimarupaka** [comment]
@mikebz That is not the requirement. This needs a custom function which reads the base setters and creates setter patterns for all the field values which have these setters as substring.

Input package:

```yaml
apiVersion: v1
kind: Deployment
metadata:
  name: nginx # kpt-set: ${name}
  namespace: nginx-space
```

```yaml
apiVersion: kpt.dev/v1alpha2
kind: Kptfile
pipeline:
  mutators:
    - image: gcr.io/kpt-fn/upsert-resource:unstable
      configMap:
         name: nginx
```

```
kpt fn eval --image gcr.io/kpt-fn/new-fn:v0.1 --include-meta-resources
```

Transformed resource:

```yaml
apiVersion: v1
kind: Deployment
metadata:
  name: nginx # kpt-set: ${name}
  namespace: nginx-space # kpt-set: ${name}-space
```
