### ISSUE TITLE
Bug: kpt randomly changes the location of isSet on pkg update

### ISSUE THREAD

**Issue by karlkfi** [GoogleContainerTools/kpt#1381]
Several times now I've done a kpt pkg update and it's re-ordered the isSet=true field in the Kptfile. It's not clear why this happens and it has no real negative effect, but it makes the file different when it doesn't need to be.

I think this is probably a Go-ism with randomly sorted maps. I think there's usually a way to force alphanumeric sorting in yaml formatting which might fix this issue.

Mostly i've been working in Cloud Shell, so whatever is installed automatically. It's kpt 0.36.1 now.

I copied two diffs earlier.
```
     io.k8s.cli.setters.org-id:
       x-k8s-cli:
         setter:
+          isSet: true
           name: org-id
           value: "336264466177"
-          isSet: true
```
```
 openAPI:
   definitions:
-    io.k8s.cli.setters.tenant-name:
-      x-k8s-cli:
-        setter:
-          name: tenant-name
-          value: boutique
     io.k8s.cli.setters.tenant-admin-group:
       x-k8s-cli:
         setter:
           name: tenant-admin-group
           value: boutique-admins@environblueprint.joonix.net
+    io.k8s.cli.setters.tenant-name:
+      x-k8s-cli:
+        setter:
+          name: tenant-name
+          value: boutique
```
