### ISSUE TITLE
Feature Request: Merge setters and substrs

### ISSUE THREAD

**Issue by karlkfi** [GoogleContainerTools/kpt#1383]
I suggest merging named substitutions into setters, so that the evaluated substitution becomes the default value of the setter. 

This would enable:
- substrs (as setters) can be inherited into sub-packages
- substrs (as setters) can be overridden at the package or sub-package level with `kpt cfg set`

Package Example:
```
openAPI:
  definitions:
    io.k8s.cli.setters.project-id:
      x-k8s-cli:
        setter:
          name: project-id
          default: ${tenant}-${environ}-${org}-${project-id-random-suffix}
```

Sub-Package Example:
```
openAPI:
  definitions:
    io.k8s.cli.setters.project-id:
      x-k8s-cli:
        setter:
          name: project-id
          required: true
```

**Comment by karlkfi** [comment]
I keep running into cases where I want this.

In the latest example, I was refactoring a gke-cluster package into 1 parent parent with 2 sub-packages (cluster & subnet) and I needed to share the subnet name (a substitution) between the two packages. But there's no way to do that right now, because substitutions aren't inherited and can't be overridden like setter defaults.

If I could set a substitution as the default value for a setter in the parent package, I could have inherited it into setters in the sub-packages, avoiding duplication of the substitution pattern and allowing the default substitution to be overridden, to make the package more re-usable.

**Comment by phanimarupaka** [comment]
This has been addressed in next branch.

**Comment by mikebz** [comment]
@karlkfi can you please take a look here https://catalog.kpt.dev/apply-setters/v0.1/ and here https://catalog.kpt.dev/search-replace/v0.1/ ?
Do these functions help your use cases?

**Comment by karlkfi** [comment]
Not really.

The new "substitutions" don't have names, so there's no way to inherit or re-use their value.

What I wanted was a way for a parent package to have a substitution as a default value that the user could override (not possible with the new apply setters either) and then be able to inherit that value (whether it was default substitution or the user supplied override value) to a sub-package as a named setter. That way sub-packages could be more generic and then grouped together with specific parent packages that link the sub-packages using shared inputs with default substitutions.

This would allow me to do things like re-use a generic gke cluster package for shared-vpc or local-vpc with different parent packages that specify substitutions as default values.

**Comment by phanimarupaka** [comment]
Since we don't have named substitutions anymore, the expanded pattern should be added to the resources in both parent and subpackage. Then all the setter values are by default inherited by the subpackage.

```yaml
# wordpress/svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: wordpress-dev-bar-xyza # kpt-set: ${tenant}-${environ}-${org}-${project-id-random-suffix}
```

```yaml
# wordpress/Kptfile
apiVersion: kpt.dev/v1alpha2
kind: Kptfile
pipeline:
  mutators:
    - image: gcr.io/kpt-fn/apply-setters:v0.1
      configMap:
        tenant: wordpress
        environ: dev
        org: bar
        project-id-random-suffix: xyza
```

```yaml
# wordpress/mysql/Kptfile
apiVersion: kpt.dev/v1alpha2
kind: Kptfile
pipeline:
  mutators:
    - image: gcr.io/kpt-fn/apply-setters:v0.1
      configMap:
        tenant: mysql
        environ: dev
        org: bar
        project-id-random-suffix: xyza
```

```yaml
# wordpress/mysql/svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: mysql-dev-bar-xyza # kpt-set: ${tenant}-${environ}-${org}-${project-id-random-suffix}
```

In kpt v1, if parent package and child package have same setter name, the setter value from parent setter takes precedence no matter what. You can't override the setter value of child package using `kpt fn render` workflow. However, there is a way to do that, if you want child package to have different value for same setter name (e.g. tenant), you should explicitly run eval on the child package.

```
kpt fn render wordpress
kpt fn render wordpress/mysql/ --image gcr.io/kpt-fn/apply-setters:v0.1 -- tenant=mysql
```

We are working on filtering packages while render which is scoped for post v1. Does this address your issue?
