### ISSUE TITLE
Feature Request: kpt cfg list-setters --include-subst should include rendered substitution values

### ISSUE THREAD

**Issue by karlkfi** [GoogleContainerTools/kpt#1405]
Right now, if you use `kpt cfg list-setters --include-subst` it only shows the content from the Kptfile. For substitutions that's the name, pattern, and references. 

I would like the command to include a column that renders the pattern based on the values of the references. 

This would help validate that the substitutions are working as designed and help look for more more values that need to be commented to use those substitutions.

**Comment by mikebz** [comment]
@karlkfi what is the intent here?  Are you trying to figure out what the config is going to look like after you are done applying the substitutions?

**Comment by karlkfi** [comment]
Yes, for checking that your substitution produces the desired value.

This would also make it easier to hide complexity by taking the output of a substitution and using it as input to another package.

This is related to:
- https://github.com/GoogleContainerTools/kpt/issues/1424
- https://github.com/GoogleContainerTools/kpt/issues/1383

**Comment by mikebz** [comment]
using the exact things you are after you want to use an example like helloworld-set

helloworld-set

```
apiVersion: kpt.dev/v1alpha2
kind: Kptfile
metadata:
  name: helloworld-set
info:
  description: kpt example
pipeline:
  mutators:
    - image: gcr.io/kpt-fn/apply-setters:unstable
      configMap:
        replicas: 5
        image: gcr.io/kpt-dev/helloworld-gke
        tag: latest
        http-port: 80
```

and the deployment is:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-gke
  labels:
    app: hello
spec:
  replicas: 5 # kpt-set: ${replicas}
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - name: helloworld-gke
        image: gcr.io/kpt-dev/helloworld-gke:v0.3.0 # kpt-set: ${image}:${tag}
        ports:
        - name: http
          containerPort: 80 # kpt-set: ${http-port}
        env:
        - name: PORT
          value: "80" # kpt-set: ${http-port}
```

So you'd like to get the final string of the image after all the substitutions have been done?

We have a function:
```
kpt fn eval . --image gcr.io/kpt-fn/search-replace:unstable -- by-path='spec.**.image'
[RUNNING] "gcr.io/kpt-fn/search-replace:unstable"
[PASS] "gcr.io/kpt-fn/search-replace:unstable"
  Results:
    [INFO] Matched field value "gcr.io/kpt-dev/helloworld-gke:v0.3.0 # kpt-set: ${image}:${tag}" in file "deploy.yaml" in field "spec.template.spec.containers[0].image"
```
Maybe what we need to do is make sure that the function outputs the result in a way that's easy to consume?
