### ISSUE TITLE
All functions should accept the ConfigMap format input

### ISSUE THREAD

**Issue by Shell32-Natsu** [GoogleContainerTools/kpt#1487]
User can use `key: value` in `configMap` field in pipeline. It will be converted to
```
...
kind: ConfigMap
metadata:
  name: ...
data:
  key: value
```

Curated functions should do it best to understand this input format. Currently we need to update set-label and set-annotation .

**Comment by Shell32-Natsu** [comment]
cc @droot @mengqiy

**Comment by mengqiy** [comment]
> User can use `key: value` in configMap field in pipeline.

Can you please give an example for this?

**Comment by Shell32-Natsu** [comment]
```
apiVersion: kpt.dev/v1alpha2
kind: Kptfile
metadata:
  name: app-with-db
pipeline:
  mutators:
  - image: gcr.io/kpt-fn/set-label:unstable
    configMap:
      foo: bar
```
