### ISSUE TITLE
Curated functions should use CRD for advanced config

### ISSUE THREAD

**Issue by Shell32-Natsu** [GoogleContainerTools/kpt#1498]
set-label and set-annotation are using ConfigMap for advanced config in a wrong way.

Needs to rewrite this part in set-label, set-annotation and set-namespace.

**Comment by mengqiy** [comment]
Function config should have schema if it's more than simple key-value pairs. Having schema can enable other tools e.g. IDE can use the schema to help function users write function config.
It doesn't need to be a real server-side CRD, but it can be a client-side equivalent of CRD (i.e. looks like a KRM but doesn't need to be installed in the server).
kubebuilder can be used to generate client-side CRDs https://book.kubebuilder.io/reference/generating-crd.html

**Comment by Shell32-Natsu** [comment]
Use kubebuilder to generate CRD schema sounds very good to me.

**Comment by Shell32-Natsu** [comment]
According to KRM function [spec](https://github.com/kubernetes-sigs/kustomize/blob/master/cmd/config/docs/api-conventions/functions-spec.md), the function config CRD should be put in `functionConfig` field in the `ResourceList`. 

Example layout for the function config CRD:
```yaml
apiVersion: kpt.dev/v1
kind: SetNamespace # depending on function
metadata:
  name: SetNamespaceConfig
# particular fields depend on function
namespace: test
fieldSpecs:
- path: sepc/selector/namespace
  group: MyGroup
  Kind: MyResource
...
```
