### ISSUE TITLE
kpt substitutions not working for empty string value

### ISSUE THREAD

**Issue by milowe** [GoogleContainerTools/kpt#1518]
### Expected behavior
Substitution picking up and using empty string value
### Actual behavior
kpt cfg set fails with message that body must be of type string: "null"
(This worked in version 0.37.1)
### Information
kpt version 0.38.0 
### Steps to reproduce the behavior
This snippet would reproduce the error
```
    io.k8s.cli.setters.foo:
      type: string
      x-k8s-cli:
        setter:
          name: foo
          value: ""

    io.k8s.cli.substitutions.bar:
      x-k8s-cli:
        substitution:
          name: bar
          pattern: something.FOO
          values:
          - marker: FOO
            ref: '#/definitions/io.k8s.cli.setters.foo'
```
