### ISSUE TITLE
setters for list of objects

### ISSUE THREAD

**Issue by bharathkkb** [GoogleContainerTools/kpt#1533]
### Is your feature request related to a problem? Please describe.
Setting a list of objects is a common requirement when dealing with Config Connector resources. For instance, when creating a private [DNSManagedZone](https://cloud.google.com/config-connector/docs/reference/resource-docs/dns/dnsmanagedzone) I would like to associate N VPCs with this resource and KCC requires I pass in a list of `privateVisibilityConfig.networks` objects.

### Describe the solution you'd like

Support setting and validating [schemas](https://swagger.io/docs/specification/data-models/data-types/#ctxM:~:text=and%20contain%20objects%3A) like
```yaml
type: array
items:
  type: object
  properties:
    id:
      type: integer
```

### Additional context

**Comment by mikebz** [comment]
@bharathkkb just to make sure I understand.  You'd like to set a thing like `networks`

```
  privateVisibilityConfig:
    networks:
    - networkRef:
        external: string
        name: string
        namespace: string
```

which can be any number of networks and it's a complex type instread of a string.

Is that correct?

I believe @phanimarupaka is in the process of designing setters in the `next` branch so would be great feedback for his design.
