### ISSUE TITLE
kptfile spec doesn't allow non-string values

### ISSUE THREAD

**Issue by karlkfi** [GoogleContainerTools/kpt#1591]
### Expected behavior

I expect the following to parse correctly, accepting a non-string value and validating the type after parsing the Kptfile:

```
io.k8s.cli.setters.max-node-count:
      x-k8s-cli:
        type: integer
        setter:
          name: max-node-count
          value: 2
```

### Actual behavior

The value field is a string in Go, so the integer fails to parse with the error:

```
error: json: cannot unmarshal number into Go struct field setter.setter.value of type string
```

This requires the value to be a string, which is confusing:

```
io.k8s.cli.setters.max-node-count:
      x-k8s-cli:
        type: integer
        setter:
          name: max-node-count
          value: "2"
```
