### ISSUE TITLE
`kpt fn run` should warn with declarative exec functions and --enable-exec  not set

### ISSUE THREAD

**Issue by howardjohn** [GoogleContainerTools/kpt#1625]
### Is your feature request related to a problem? Please describe.
I set up a YAML like
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: test
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: some-file
        network: true
    config.kubernetes.io/local-config: "true"
```

and ran `kpt fn run --log-steps -v9`. Nothing happens and there is no output
### Describe the solution you'd like

Some logs to indicate why the function is not run

### Additional context
