### ISSUE TITLE
Remove `config` in function spec

### ISSUE THREAD

**Issue by phanimarupaka** [GoogleContainerTools/kpt#1661]
I was trying `kpt fn render` and I provided a path to config option expecting that it would read from the path.

```
pipeline:
  mutators:
  - image: gcr.io/kpt-fn/apply-setters:unstable
    config: ./fn-config.yaml
```

But I received an error: `error: failed to run pipeline in package . pipeline run: . missing Resource metadata` which din't help me to figure out what's wrong. Sunil helped me with debugging and the mistake was that I passed path to `config` but it should be `configPath`. 

```
pipeline:
  mutators:
  - image: gcr.io/kpt-fn/apply-setters:unstable
    configPath: ./fn-config.yaml
```

This worked.

I know the error message can be improved but I am not sure if we should provide so many options to enter the values in Kptfile. I would suggest to separate the function configs from Kptfile. Package consumers can just open the fn-values.yaml file and provide the inputs. Having too many options(config vs configPath vs configMap) is confusing. Having separate fn-values.yaml would make Cloud Code to provide authoring assistance where providing it though config option can't.

**Comment by frankfarzan** [comment]
Are you suggesting we don't have inline KRM using `config`? There's prior art with Kustomize allow inlining, we should assess the pros/cons before deciding. I agree having separate resources enables schema validation.

**Comment by phanimarupaka** [comment]
Yes. Both inline `config` and `configMap`. When in doubt we can start simple with simple option `configPath` and add the support later for other 2 options. WDYT?

**Comment by frankfarzan** [comment]
I think we need to keep `configMap`, otherwise simple cases are too verbose. `configMap` doesn't have the schema/validation problem (it's simple key/value).

**Comment by droot** [comment]
@phanimarupaka and me had a chat about it. Two things discussed:

- We don't have a strong use-case for inline config. So may be we don't support it initially and support it later. This can remove the confusion that Phani ran into.
- Extending the configMap to generic function args where it can be take key-value where value can be any primitive type int, string, list-of-primitive-types. It can be even renamed to 'args`

An example
```yaml

pipeline:
  mutators:
    - image: gcr.io/kpt-fn/apply-setters:unstable
      args:
          replicas: 2
          envs:
            - dev
            - staging
    - image: gcr.io/kpt-fn/set-namespace:unstable
      argsFile: ./ns.yaml

```

**Comment by frankfarzan** [comment]
Different discussions:

1. naming: `function config` is part of functions spec. If we want to name this to `args` or `params` (both are better names than `function config`) everywhere, it will be a backwards incompatible change to function spec. I wouldn't have it be called different things in Kpefile schema versus Functions spec.
2. For non-primitive value (`args`), it still needs to be converted to a ConfigMap as part of `ResourceList.functionConfig`? If so, this sugar coating seems to be abusing ConfigMap. In those cases, we want a custom resource, no?

**Comment by phanimarupaka** [comment]
1. We should get rid of the concept of configMap both in Kptfile and accepting as function spec input. ConfigMap is extremely restrictive and simple inputs like `replicas: 3` can't be passed via configMap as `3` is non-string there. We should have new CRD `FunctionParams`(or `FunctionArgs`) which has similar schema as configMap but is more expressive in-terms of allowing primitive types(and arrays). Most of the functions like `apply-setters`, `search-replace`, `set-replicas`(which might be developed in future) etc. can leverage `FunctionParams` to obtain more expressive inputs.

e.g.
```
pipeline:
  mutators:
    - image: gcr.io/kpt-fn/apply-setters:unstable
      functionParams:
          replicas: 2
          envs:
            - dev
            - staging
```
or
```
apiVersion: kpt.dev/v1alpha2
kind: FunctionParams
data:
  replicas: 2
  environments:
    - dev
```

2. Functions which need complex inputs can have their own CRDs.(`apply-patch` etc.)
