### ISSUE TITLE
Kpt inserts !!int YAML tags for string setters that had integer values

### ISSUE THREAD

**Issue by ashlineldridge** [GoogleContainerTools/kpt#1673]
### Expected behavior

I'd expect that if a setter is defined with type `string` then integer tags would not be added to the output YAML.

### Actual behavior

Given the a directory containing the following Kptfile:

```yaml
apiVersion: kpt.dev/v1alpha1
kind: Kptfile
metadata:
  name: my-account
packageMetadata:
  shortDescription: Example
openAPI:
  definitions:
    io.k8s.cli.setters.account-id:
      type: string
      x-k8s-cli:
        setter:
          name: account-id
          value: "123"
          isSet: true
```

And a single resource file:

```yaml
apiVersion: example.com/v1alpha1
kind: Account
metadata:
  name: my-account
spec:
  accountID: 123 # {"$kpt-set":"account-id"}
```

If I run `kpt cfg set . account-id abc`, then the resource file is modified to:

```yaml
apiVersion: example.com/v1alpha1
kind: Account
metadata:
  name: my-account
spec:
  accountID: !!int abc # {"$kpt-set":"account-id"}
```

### Information

Kpt version: 0.38.1
