### ISSUE TITLE
kpt fn may modify the comments at the beginning of the resource file

### ISSUE THREAD

**Issue by Shell32-Natsu** [GoogleContainerTools/kpt#1706]
`resources.yaml`:
```
# comment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: foo
spec:
  replicas: 3
```

`function.sh`:
```
sed -e 's/foo/bar/'
```

kpt command:
```
kpt fn eval . --dry-run --exec-path ./function.sh
```

Output:
```
# comment
apiVersion: apps/v1 # comment
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: bar
  annotations:
    config.kubernetes.io/path: 'resources.yaml'
spec:
  replicas: 3
```

A comment is added after the first line of resource. Looks like this a problem in kyaml.

---

Another similar bug about the comment is, if we change the `resources.yaml` file to this:
```
# comment
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: foo
spec:
  replicas: 3
```

Than the comment in first line will be removed after kpt fn. 

Output:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: bar
  annotations:
    config.kubernetes.io/path: 'resources.yaml'
spec:
  replicas: 3
```
