### ISSUE TITLE
Empty string setter throws OpenAPI validation when used with subst

### ISSUE THREAD

**Issue by bharathkkb** [GoogleContainerTools/kpt#1761]
### Expected behavior
`kpt cfg set . foo testnew` works without error

This used to work in 0.38.1
```
 ./kpt version
0.38.1
kpt cfg set . foo testnew
./
set 2 field(s) of setter "foo" to value "testnew"
```

### Actual behavior

In 0.39
```
kpt version
0.39.1
kpt cfg set . foo testnew
./
error: The input value doesn't validate against provided OpenAPI schema: validation failure list:
bar in body must be of type string: "null"
```

### Information

 Kpt Version: 0.39.1

Files:

```yaml
foo: "test" # {"$kpt-set":"foo"}
baz: "test-baz" # {"$kpt-set":"baz"}
```
```yaml
apiVersion: kpt.dev/v1alpha1
kind: Kptfile
metadata:
  name: test
openAPI:
  definitions:
    io.k8s.cli.setters.foo:
      type: string
      description: test
      x-k8s-cli:
        setter:
          name: foo
          value: test
    io.k8s.cli.setters.bar:
      type: string
      description: test
      x-k8s-cli:
        setter:
          name: bar
          value: ""
    io.k8s.cli.substitutions.baz:
      x-k8s-cli:
        substitution:
          name: baz
          pattern: ${foo}${bar}-baz
          values:
          - marker: ${foo}
            ref: '#/definitions/io.k8s.cli.setters.foo'
          - marker: ${bar}
            ref: '#/definitions/io.k8s.cli.setters.bar'
```

### Steps to reproduce the behavior
