### ISSUE TITLE
gcr.io/kpt-fn/set-namespace deletes comments in file

### ISSUE THREAD

**Issue by howardjohn** [GoogleContainerTools/kpt#1815]
Start with file:
```yaml
# This object and its stored inventory is subsequently
# used to calculate the set of objects to automatically
# delete (prune), when an object is omitted from further
# applies. When applied, this "inventory object" is also
# used to identify the entire set of objects to delete.
#
# NOTE: The name of this inventory template file
# does NOT have any impact on group-related functionality
# such as deletion or pruning.
#
apiVersion: v1 # NOTE: auto-generated. Some fields should NOT be modified.
kind: ConfigMap
metadata:
  # DANGER: Do not change the inventory object namespace.
  # Changing the namespace will cause a loss of continuity
  # with previously applied grouped objects. Set deletion
  # and pruning functionality will be impaired.
  namespace: metallb-system
  # NOTE: The name of the inventory object does NOT have
  # any impact on group-related functionality such as
  # deletion or pruning.
  name: inventory-82029660
  labels:
    # DANGER: Do not change the value of this label.
    # Changing this value will cause a loss of continuity
    # with previously applied grouped objects. Set deletion
    # and pruning functionality will be impaired.
    cli-utils.sigs.k8s.io/inventory-id: e947bb0e-56f3-450c-96ed-8c5ecff10017
```

Run:
`kpt fn run --image gcr.io/kpt-functions/set-namespace .`

Results:
```diff
diff --git a/inventory-template.yaml b/inventory-template.yaml
index f40ca14..398c152 100644
--- a/inventory-template.yaml
+++ b/inventory-template.yaml
@@ -1,5 +1,3 @@
-# This object and its stored inventory is subsequently
-# used to calculate the set of objects to automatically
 # delete (prune), when an object is omitted from further
 # applies. When applied, this "inventory object" is also
 # used to identify the entire set of objects to delete.
```

Run again:
```diff
diff --git a/inventory-template.yaml b/inventory-template.yaml
index f40ca14..28e9ded 100644
--- a/inventory-template.yaml
+++ b/inventory-template.yaml
@@ -1,7 +1,3 @@
-# This object and its stored inventory is subsequently
-# used to calculate the set of objects to automatically
-# delete (prune), when an object is omitted from further
-# applies. When applied, this "inventory object" is also
 # used to identify the entire set of objects to delete.
 #
 # NOTE: The name of this inventory template file
```

`kpt version is `0.39.2`.

I am not sure if this is a bug with set-namespaces or kpt in general.
