### ISSUE TITLE
apply-setters function does not apply substitutions

### ISSUE THREAD

**Issue by johnbelamaric** [GoogleContainerTools/kpt#1931]
### Expected behavior
I would expect the apply-setters function to work in a manner identical to `kpt cfg set`.

### Actual behavior
Substitutions are ignored, which makes them useless if you want to use the package in an automation pipeline with apply-setters.

### Information

Kpt Version: 0.39.2

### Steps to reproduce the behavior
Run apply-setters against a package with substitutions defined. Only the setters are applied.

**Comment by mikebz** [comment]
@phanimarupaka can you please take a look at this one using kpt `next` branch?

**Comment by mikebz** [comment]
@johnbelamaric just to be clear you have tried using this with kpt `next` build or you tried the new function with old kpt?

https://catalog.kpt.dev/apply-setters/v0.1/

Here is the example:
```
apiVersion: v1
kind: Deployment
metadata:
  name: nginx-deployment # kpt-set: ${image}-deployment
spec:
  replicas: 1 # kpt-set: ${replicas}
```
where there is a substitution.  Is this the thing that you tried and it's not working for you?
