### ISSUE TITLE
kpt fn eval --exec should support cmd+args

### ISSUE THREAD

**Issue by mortent** [GoogleContainerTools/kpt#2069]
Starting with the following resource: 

```
apiVersion: v1
kind: Namespace
metadata: # this is a test
  name: foo
```

And I run the label_namespace function:

```
kpt fn source . | node <path to func> -d label_name=color -d label_value=orange | kpt fn sink .
```

The result is:

```
apiVersion: v1
kind: Namespace
metadata:
  name: foo
  labels:
    color: orange
```

The expectation here is that the comment on the `metadata` field should be preserved.
