### ISSUE TITLE
fix schema for `resourceRef` in kyaml

### ISSUE THREAD

**Issue by natasha41575** [GoogleContainerTools/kpt#2091]
The [ResourceRef schema in the kpt function SDKs](https://github.com/GoogleContainerTools/kpt-functions-sdk/blob/6d56c218eb8d72b0a56366b7b3927105d4068ec3/ts/kpt-functions/src/types.ts#L383) is 

```
resourceRef:
    apiVersion: apps/v1
    kind: Deployment
    namespace: ''
    name: nginx-deployment
```

and [the ResourceRef schema in kyaml](https://github.com/kubernetes-sigs/kustomize/blob/0f614e92f72f1b938a9171b964d90b197ca8fb68/kyaml/yaml/types.go#L139) which is used by kpt [here](https://github.com/GoogleContainerTools/kpt/blob/b6ad66da7fb3afd457ae551f5d3eeac707e9eaf0/pkg/api/fnresult/v1alpha2/types.go#L39) is:

```
resourceRef:
    apiVersion: apps/v1
    kind: Deployment
    metadata: 
      namespace: ''
      name: nginx-deployment
```

Our current workaround (https://github.com/GoogleContainerTools/kpt/pull/2086) is to duplicate the `ResultItem` type from kyaml, but change the type used for `resourceRef`. Instead of duplicating this type, we should fix it upstream in kyaml.

We will also need to make sure both function orchestrators (kpt and kustomize) are still backwards compatible with the old schema. 

cc @droot
