### ISSUE TITLE
create-setters adds incorrect comments

### ISSUE THREAD

**Issue by mortent** [GoogleContainerTools/kpt#2199]
The input resources are:

dep.yaml:
```yaml
apiVersion: v1
kind: MyKind
metadata:
  name: foo
environments:
  - dev
  - stage
```

cm.yaml:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: create-setters-fn-config
data:
  name: foo
  env: |
    - dev
    - stage
    - foo
```

Running the following command:
```sh
kpt fn eval --image gcr.io/kpt-fn/create-setters:v0.1 --fn-config ./cm.yaml
```

The result is:

cm.yaml
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: create-setters-fn-config
data:
  name: foo # kpt-set: ${name}
  env: | # kpt-set: - dev
    # - stage
    # - ${name}
    - dev
    - stage
    - foo
```

dep.yaml:
```yaml
apiVersion: v1
kind: MyKind
metadata:
  name: foo # kpt-set: ${name}
environments:
  - dev
  - stage
```

The comments added to the `env` list does not look correct.
