### ISSUE TITLE
Easy way to set annotation on all resources with another annotation

### ISSUE THREAD

**Issue by morgante** [GoogleContainerTools/kpt#2315]
For all resources which have a certain annotation (`local-config: true`), I would like to add another annotation (`configmanagement.gke.io/managed: disabled`).

What is the best way to accomplish this using kpt v1? Ideally with a one-line imperative command.

**Comment by mikebz** [comment]
@mengqiy @phanimarupaka I'd like your help here.  Morgante here is looking to add an annotation to resources that already have another annotation.  What can we do to help him solve this problem?

The issue is the CS doesn't currently respect the local-config annotation.

**Comment by mengqiy** [comment]
In the long term, https://github.com/GoogleContainerTools/kpt/issues/2015 and `set-annotations` can work together to solve this problem.

In the near term, the [`starlark`](https://catalog.kpt.dev/starlark/v0.1/) can be used with the following function config:
```yaml
apiVersion: fn.kpt.dev/v1alpha1
kind: StarlarkRun
metadata:
  name: set-annotation
source: |
  def conditionallySetAnnotation(resources):
    for resource in resources:
      if "config.kubernetes.io/local-config" in resource["metadata"]["annotations"] and (resource["metadata"]["annotations"]["config.kubernetes.io/local-config"] == True or resource["metadata"]["annotations"]["config.kubernetes.io/local-config"] == "true"):
        resource["metadata"]["annotations"]["configmanagement.gke.io/managed"] = "disabled"
  conditionallySetAnnotation(ctx.resource_list["items"])
```
