### ISSUE TITLE
render can break valid yaml

### ISSUE THREAD

**Issue by ryane** [GoogleContainerTools/kpt#2321]
### Expected behavior

Rendering a kpt package shouldn't break otherwise valid yaml.

### Actual behavior

In some cases, `kpt fn render` (or imperatively running any kpt fns on the package) will result in invalid yaml.

### Information

```
$ kpt version
1.0.0-alpha.10
```

### Steps to reproduce the behavior

```
mkdir test
cd test
kpt pkg init
cat <<EOF > service.yaml
apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  selector:
    app: nginx
  ports:
    - name: http
      port: 80
      targetPort: 8080
      nodePort: null
EOF
```

At this point, I have a kpt pkg containing a service that other tools recognize as valid:

```
$ kubeval --strict service.yaml
PASS - service.yaml contains a valid Service (nginx)

$ kubectl apply -f service.yaml
service/nginx configured
```

But, if I render the package:

```
$ kpt fn render
Package "test":
Successfully executed 0 function(s) in 1 package(s).

$ kubeval --strict service.yaml
ERR  - Failed to decode YAML from service.yaml: error converting YAML to JSON: yaml: cannot decode !!null `null` as a !!int

$ kubectl apply -f service.yaml
error: error parsing service.yaml: error converting YAML to JSON: yaml: cannot decode !!null `null` as a !!int

$ cat service.yaml
apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  selector:
    app: nginx
  ports:
    - name: http
      port: 80
      targetPort: 8080
      nodePort: !!int null
```

Based on the api type of `nodePort`, I can kind of guess why this might be happening but, since other tools support it, introducing kpt probably shouldn't break things.
