### ISSUE TITLE
`kpt fn render` reformats causes undesired field reordering

### ISSUE THREAD

**Issue by morgante** [GoogleContainerTools/kpt#2332]
When using `kpt fn render`, comments in my yaml files are arbitrarily relocated and disconnected from their intended location.

For example, if I run `kpt fn render` on this `ConfigMap`:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: setters-config
data:
  # This should be the name of your Config Controller instance
  cluster-name: cluster-name
  # This should be the project where you deployed Config Controller
  project-id: project-id
  project-number: "1234567890123"
  # You can leave these defaults
  namespace: config-control
  deployment-repo: deployment-repo
  source-repo: source-repo
```

It will reorganize the entire file and disconnect comments from their intended location:
```
apiVersion: v1
kind: ConfigMap
metadata: # kpt-merge: /setters-config
  name: setters-config
data:
  # You can leave these defaults
  namespace: config-control
  # This should be the name of your Config Controller instance
  cluster-name: cluster-name
  deployment-repo: deployment-repo
  # This should be the project where you deployed Config Controller
  project-id: project-id
  project-number: "1234567890123"
  source-repo: source-repo
```

**Desired result**: The order of fields in the data map should not be changed and comments should stay connected to the correct lines.

kpt version: v1.0-beta
