### ISSUE TITLE
How to get kpt v1 YAML changes match kubernetes YAML format?

### ISSUE THREAD

**Issue by taisph** [GoogleContainerTools/kpt#2342]
With kpt v0, YAML list indentation follows kubernetes formatting like below:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
spec:
  template:
    spec:
      containers:
      - name: test
        env:
        - name: foo
          value: "bar"
```

With kpt v1 (fn fix and apply-setters) all lists gets indented like below:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
spec:
  template:
    spec:
      containers:
        - name: test
          env:
            - name: foo
              value: "bar"
```
