### ISSUE TITLE
Render doesn't always handle `null` values correctly

### ISSUE THREAD

**Issue by mortent** [GoogleContainerTools/kpt#2345]
Sometimes `null` values are turned into strings.

If we have the following resources:
```
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: customs.custom.io
  creationTimestamp: null
```
 in a package with an empty pipeline, running
```
kpt fn render
```
produces the following result:
```
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: customs.custom.io
  creationTimestamp: "null"
```
The null value for `creationTimestamp` has become a string with the value `"null"`.

This doesn't seem to happen for other fields, so I suspect this is related to the type in the openapi schema for the `creationTimestamp` field.
