### ISSUE TITLE
Kpt function "configPath" cannot find files in subdirectories 

### ISSUE THREAD

**Issue by yuwenma** [GoogleContainerTools/kpt#2346]
### Expected behavior

configPath (and --fn-config flag) can find files in both current directory ./fn-config.yaml and subdirectories ./*/fn-config.yaml 

### Actual behavior

configPath can only accept path in current directory. When specified a subdirectory:
- --fn-config in `kpt fn eval` gives "error: missing function config file: config/search-replace.yaml" 
- `.pipeline.mutators[n].configPath` gives error  
```yaml
Kptfile is invalid:
Field: `pipeline.mutators[0].configPath`
Value: "config/search-replace.yaml"
Reason: functionConfig must exist in the current package
```

#### To reproduce `kpt fn render`
1. Create a `search-replace.yaml` file as the following content and put it under a subdirectory `config/search-replace.yaml`
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: resize
data:
  by-path: spec.replicas
  by-value: "3"
  put-value: "5"
```
2. Update the `Kptfile` as below:
```yaml
apiVersion: kpt.dev/v1
kind: Kptfile
metadata:
  name: declarative-kpt
pipeline:
  mutators:
    - image: gcr.io/kpt-fn/search-replace:v0.1
      configPath: config/search-replace.yaml
```
3. add a sample deployment.yaml in current directory
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx
spec:
  replicas: 5
  template:
    spec:
      containers:
        - name: nginx
          image: "gcr.io/nginx:1.14.2"
```
4. run `kpt fn render . `

#### To reproduce `kpt fn eval`
run `kpt fn eval --image=gcr.io/kpt-fn/search-replace:v0.1 --fn-config=config/search-replace.yaml`

#### A workable configPath

By moving `config/search-replace.yaml` to current directory, both declarative and imperative kpt fn work.

```bash
mv config/search-replace.yaml .
kpt fn eval --image=gcr.io/kpt-fn/search-replace:v0.1 --fn-config=search-replace.yaml
[RUNNING] "gcr.io/kpt-fn/search-replace:v0.1"
[PASS] "gcr.io/kpt-fn/search-replace:v0.1"
```
