### ISSUE TITLE
Update the behavior of set-namespace function

### ISSUE THREAD

**Issue by droot** [GoogleContainerTools/kpt#2397]
Hey all, I'm currently struggling with the gcr.io/kpt-fn/set-namespace:v0.1.4 function and I want to share it with you.
I have the following resource which I want to change the namespace of. Not only on metadata.namespace level but also under subjects[*].namespace. While the documentation of set-namespace states that also subject sections will change it does not work for me. My kpt version is 1.0.0-beta.1

```
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    app: confluent-for-kubernetes
    # [...]
  name: confluent-operator
  namespace: default
subjects:
- kind: ServiceAccount
  name: confluent-for-kubernetes
  namespace: default
roleRef:
  kind: Role
  name: confluent-operator
  apiGroup: rbac.authorization.k8s.io
```

As the documentation states it is possible to provide a field additionalNamespaceFields as a function parameter. So in the following constellation it works.
My Kptfile
```
apiVersion: kpt.dev/v1
kind: Kptfile
metadata:
  name: confluent-for-kubernetes
info:
  site: confluentinc/confluent-for-kubernetes
  description: confluent-for-kubernetes package
pipeline:
  mutators:
    - image: gcr.io/kpt-fn/set-namespace:v0.1.4
      configPath: fn-set-namespace.yaml
```
My fn-set-namespace.yaml custom resource
```
apiVersion: fn.kpt.dev/v1alpha1
kind: SetNamespace
metadata:
  name: confluent-for-kubernetes
additionalNamespaceFields:
  - kind: RoleBinding
    create: false
    group: rbac.authorization.k8s.io
    path: subjects/namespace
    version: v1
namespace: confluent-for-kubernetes
```
`kpt fn render . `produces the correct result in this case. :white_check_mark:
The problem is: Because I want to render all Kpt packages in-place and commit the result into the the same directory ArgoCD uses for deploying the KRDs I must not place any CRDs which ArgoCD is not aware of (e.g. SetNamespace).
So far so good: As the docs for set-namespace state the function also accepts a config map as functionConfig which I'll have to declare inline, because I do not want ArgoCD to pick it up.
However providing the functionConfig inline with the following Kptfile
```
apiVersion: kpt.dev/v1
kind: Kptfile
metadata:
  name: confluent-for-kubernetes
info:
  site: confluentinc/confluent-for-kubernetes
  description: confluent-for-kubernetes package
pipeline:
  mutators:
    - image: gcr.io/kpt-fn/set-namespace:v0.1.4
      configMap:
        namespace: confluent-for-kubernetes
        additionalNamespaceFields:
          - kind: RoleBinding
            create: false
            group: rbac.authorization.k8s.io
            path: subjects/namespace
            version: v1
```
does not work :x:
`kpt fn render .` errors with
Error: Kptfile at "[... snip snip ...]/confluent-for-kubernetes" can't be read.
Details:
yaml: unmarshal errors:
  line 14: cannot unmarshal !!seq into string
Is this a bug?
Is there another way to specify the config inline?
And also important: Shouldn't the function gcr.io/kpt-fn/set-namespace:v0.1.4 automatically change the namespace under subjects without the additionalNamespaceFields parameter?
Sorry for the wall of text

**Comment by droot** [comment]
This was originally reported by a user in Slack channel. Here is the link to the original post:

https://kubernetes.slack.com/archives/C0155NSPJSZ/p1626279199088800

**Comment by borismw** [comment]
OP here, thanks for filing this issue. Maybe needs to be split, idk. If so, I'm willing to help and provide details.

**Comment by mengqiy** [comment]
Re. set-namespace function doesn't change `subjects[*].namespace`, this seems to be a bug. I will fix it.

The following is not a valid Kptfile since only string to string key-value pair is allowed the `configMap` field. The `additionalNamespaceFields` field is a list of maps.
 
```
apiVersion: kpt.dev/v1
kind: Kptfile
metadata:
  name: confluent-for-kubernetes
info:
  site: confluentinc/confluent-for-kubernetes
  description: confluent-for-kubernetes package
pipeline:
  mutators:
    - image: gcr.io/kpt-fn/set-namespace:v0.1.4
      configMap:
        namespace: confluent-for-kubernetes
        additionalNamespaceFields:
          - kind: RoleBinding
            create: false
            group: rbac.authorization.k8s.io
            path: subjects/namespace
            version: v1
```

> kpt fn render . errors with
> Error: Kptfile at "[... snip snip ...]/confluent-for-kubernetes" can't be read.
> Details:
> yaml: unmarshal errors:
> line 14: cannot unmarshal !!seq into string

@droot The error message here is not useful and not actionable. We should fix it.

**Comment by borismw** [comment]
@mengqiy slightly OT, but could you give me a hint on how to correctly specify the `additionalNamespaceFields` parameter on an inline (within the Kptfile) function invocation?

**Comment by mengqiy** [comment]
> could you give me a hint on how to correctly specify the additionalNamespaceFields parameter on an inline (within the Kptfile) function invocation?

There is no way to achieve that.
Kptfile only supports function to use inline `configMap` as the functionConfig, but `additionalNamespaceFields` only exists in `SetNamespace` client-side CRD.

**Comment by mengqiy** [comment]
We are using the `namespace.Filter()` from the kustomize repo. It handles the resources that have `subjects` specially. e.g. `RoleBinding` or `ClusterRoleBinding`:
https://github.com/kubernetes-sigs/kustomize/blob/91b862b5563e2f601ea5ed5485379f1cac64ccfb/api/filters/namespace/namespace.go#L87-L100

You can change the `name` field in `subjects` to `default` to work around this issue.

```
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    app: confluent-for-kubernetes
    # [...]
  name: confluent-operator
  namespace: default
subjects:
- kind: ServiceAccount
  name: default # <======== using name default here
  namespace: default
roleRef:
  kind: Role
  name: confluent-operator
  apiGroup: rbac.authorization.k8s.io
```
