### ISSUE TITLE
Starlark function fails when kpt-merge comment is present

### ISSUE THREAD

**Issue by jafcrocker** [GoogleContainerTools/kpt#2438]
### Expected behavior

Starlark function should work in the presence of a `# kpt-merge: namespace/name` comment on the metadata line.  Note that this comment is added automatically by _kpt_ upon getting or updating a package. 

### Actual behavior

When a resource with the `kpt-merge` comment is present, the Starlark function emits an error.

### Information
Kpt version: 1.0.0-beta.3
Starlark function version: v0.2.1

### Steps to reproduce the behavior
Given the following files:
```
% cat Kptfile 
apiVersion: kpt.dev/v1
kind: Kptfile
metadata:
  name: starlark
info:
  description: sample description
pipeline:
  mutators:
    - image: gcr.io/kpt-fn/starlark:v0.2.1
      configMap:
        source: ""

% cat resource.yaml 
apiVersion: apps/v1
kind: Deployment
metadata: # kpt-merge: /wordpress
  name: wordpress
  labels:
    app: wordpress
```

`kpt fn render`emits an error:
```
% kpt fn render . -o stdout
Package "starlark": 
[RUNNING] "gcr.io/kpt-fn/starlark:v0.2.1"
[FAIL] "gcr.io/kpt-fn/starlark:v0.2.1"
  Results:
    [ERROR] yaml: invalid map key: map[string]interface {}{"annotations":map[string]interface {}{"config.k8s.io/id":"1", "config.kubernetes.io/index":"0", "config.kubernetes.io/path":"resource.yaml"}, "labels":map[string]interface {}{"app":"wordpress"}, "name":"wordpress"}
  Stderr:
    "[error] : yaml: invalid map key: map[string]interface {}{\"annotations\":map[string]interface {}{\"config.k8s.io/id\":\"1\", \"config.kubernetes.io/index\":\"0\", \"config.kubernetes.io/path\":\"resource.yaml\"}, \"labels\":map[string]interface {}{\"app\":\"wordpress\"}, \"name\":\"wordpress\"}"
  Exit code: 1
```
Removing the comment allows the function to work properly:
```
% sed -i "" 's/metadata:.*/metadata:/' resource.yaml

% cat resource.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress

% kpt fn render . -o stdout                         
Package "starlark": 
[RUNNING] "gcr.io/kpt-fn/starlark:v0.2.1"
[PASS] "gcr.io/kpt-fn/starlark:v0.2.1"

apiVersion: config.kubernetes.io/v1alpha1
kind: ResourceList
items:
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: wordpress
      labels:
        app: wordpress
      annotations:
        config.kubernetes.io/index: "0"
        config.kubernetes.io/path: resource.yaml
```
```

**Comment by mengqiy** [comment]
We currently "roundtrip" objects in https://github.com/GoogleContainerTools/kpt-functions-catalog/blob/9d3b022ad2d907efb8d7028d17c3fead7c96caa6/functions/go/starlark/third_party/sigs.k8s.io/kustomize/kyaml/fn/runtime/starlark/starlark.go#L142-L151 before passing to the starlark function.

Here is an example that has the issue.
When we do serialization, we get
```
apiVersion: config.kubernetes.io/v1alpha1
items: [{apiVersion: v1, kind: ConfigMap, metadata:, #  sdjfldsjf
{name: my-cm, annotations: {config.kubernetes.io/index: '0', config.kubernetes.io/path: 'app.yaml', internal.config.kubernetes.io/seqindent: 'compact', config.k8s.io/id: '1'}} data: {some-key: some-value}}]
kind: ResourceList
functionConfig:
  apiVersion: fn.kpt.dev/v1alpha1
  kind: StarlarkRun
...
```

When we try to deserialize it, obviously there is a problem around the comment. It cannot be deserialized any more.

We can avoid this problem by converting the RNode directly to map[string]interface{}.
