### ISSUE TITLE
Non actionable error message "the server could not find the requested resource"

### ISSUE THREAD

**Issue by howardjohn** [GoogleContainerTools/kpt#2453]
Facing an error when trying to apply a nearly 100% empty folder:
```
$ ls
Kptfile
$ cat Kptfile
apiVersion: kpt.dev/v1
kind: Kptfile
metadata:
  name: metallb
inventory:
  namespace: metallb-system
  name: inventory-12944758
  inventoryID: e947bb0e-56f3-450c-96ed-8c5ecff10017
kind-kind:metallb-system /tmp/tmp.HvUUA05H8A
$ kpt live apply
Error from server (NotFound): the server could not find the requested resource
```

The ResourceGroup in cluster:
```yaml
apiVersion: kpt.dev/v1alpha1
kind: ResourceGroup
metadata:
  labels:
    cli-utils.sigs.k8s.io/inventory-id: e947bb0e-56f3-450c-96ed-8c5ecff10017
  name: inventory-12944758
  namespace: metallb-system
spec:
  resources:
  - group: policy
    kind: PodSecurityPolicy
    name: controller
    namespace: metallb-system
  - kind: ConfigMap
    name: config
    namespace: metallb
  - kind: Namespace
    name: metallb
  - kind: ServiceAccount
    name: speaker
    namespace: metallb
  - group: rbac.authorization.k8s.io
    kind: Role
    name: config-watcher
    namespace: metallb
  - group: policy
    kind: PodSecurityPolicy
    name: speaker
    namespace: metallb-system
  - group: rbac.authorization.k8s.io
    kind: Role
    name: pod-lister
    namespace: metallb
  - group: rbac.authorization.k8s.io
    kind: ClusterRole
    name: metallb-system:controller
  - group: rbac.authorization.k8s.io
    kind: ClusterRoleBinding
    name: metallb-system:speaker
  - kind: ServiceAccount
    name: controller
    namespace: metallb
  - group: rbac.authorization.k8s.io
    kind: ClusterRole
    name: metallb-system:speaker
  - group: apps
    kind: Deployment
    name: controller
    namespace: metallb
  - group: rbac.authorization.k8s.io
    kind: RoleBinding
    name: config-watcher
    namespace: metallb
  - group: rbac.authorization.k8s.io
    kind: RoleBinding
    name: pod-lister
    namespace: metallb
  - group: rbac.authorization.k8s.io
    kind: ClusterRoleBinding
    name: metallb-system:controller
  - group: apps
    kind: DaemonSet
    name: speaker
    namespace: metallb
```

The error here is not actionable, as it doesn't give any information about what resource is missing, giving no next steps to debug further.

### Information
```
$ kpt version
1.0.0-beta.3
```
### Steps to reproduce the behavior
Apply configs above and run `kpt live apply`
