### ISSUE TITLE
render skips running function if pkg only contains the function config and Kptfile

### ISSUE THREAD

**Issue by bharathkkb** [GoogleContainerTools/kpt#2477]
### Expected behavior

`render` runs function and generates resources.

### Actual behavior

`render` seems to exit early if a package only contains the functionConfig and Kptfile. 
 Quick trace led me to https://github.com/GoogleContainerTools/kpt/blob/57b52103576b7a195502dc10a4ad608570095e47/internal/cmdrender/executor.go#L339-L342

`eval` works as expected.

### Information

Kpt Version: 1.0.0-beta.3

### Steps to reproduce the behavior

Example pkg with just

```yaml
# Kptfile
apiVersion: kpt.dev/v1
kind: Kptfile
metadata:
  name: example
pipeline:
  mutators:
    - image: gcr.io/kpt-fn/upsert-resource:unstable
      configPath: fn-config.yaml
```

```yaml
# fn-config.yaml
apiVersion: v1
kind: Service
metadata:
  name: myService
  namespace: mySpace
spec:
  selector:
    app: bar
```

No resource generated for render
```
 kpt fn render 
Package "test2": 
Successfully executed 0 function(s) in 1 package(s).
```

WAI for eval
```
kpt fn eval --image gcr.io/kpt-fn/upsert-resource:unstable --fn-config fn-config.yaml 
[RUNNING] "gcr.io/kpt-fn/upsert-resource:unstable"
[PASS] "gcr.io/kpt-fn/upsert-resource:unstable"
```
