### ISSUE TITLE
kpt live preview might erroneously merge objects instead of applying only the new object

### ISSUE THREAD

**Issue by dflemstr** [GoogleContainerTools/kpt#2532]
### Steps to reproduce the behavior

Using kpt 0.39.2, given a KRM file that is changed according to this diff (snippet from a [SQLUser](https://cloud.google.com/config-connector/docs/reference/resource-docs/sql/sqluser) object):

```diff
@@ -58,10 +51,7 @@
   instanceRef:
     name: software-catalog-db-instance
   password:
-    valueFrom:
-      secretKeyRef:
-        key: softwarecatalog.postgres-password
-        name: software-catalog-secrets
+    value: password
 status:
   conditions:
   - lastTransitionTime: "2021-06-29T11:30:54Z"
```

We run `kpt live diff` and the above diff is produced.  We immediately after run `kpt live preview --server-side --force-conflicts --field-manager=<elided for brevity>`.

### Expected behavior

The object passes schema validation and `kpt live preview` returns with a successful exit code

### Actual behavior

The object fails schema validation with this error:

```
SQLUser.sql.cnrm.cloud.google.com "software-catalog-db-user" is invalid: [: Invalid value: "": "spec.password" must validate one and only one schema (oneOf). Found none valid, : Invalid value: "": "spec.password" must not validate the schema (not)]
```

### Information

It would seem like the object that is submitted to the cluster is a merged version of the object that contains both the `valueFrom` and `value` field,  hence leading to a violation of the OpenAPI schema `oneOf` constraint.

Applying the object succeeds with `kpt live apply` and/or `kubectl apply -f ...`.

**Comment by mengqiy** [comment]
Have you tried `kpt live` from kpt v1?

**Comment by mortent** [comment]
I will take a look at this.

**Comment by mortent** [comment]
I am able to reproduce this. I don't think it is a problem in kpt live, but rather in either the kubectl libraries we are using or in the cluster.

I can reproduce this with kubectl starting with the following resource (in a file called sqluser.yaml):
```
  apiVersion: sql.cnrm.cloud.google.com/v1beta1
  kind: SQLUser
  metadata:
    name: sqluser-sample
  spec:
    instanceRef:
      name: sqluser-dep
    host: "%"
    password:
      valueFrom:
        secretKeyRef:
          name: sqluser-dep
          key: password
```
Apply it to the cluster:
```
$ kubectl apply -f sqluser.yaml
sqluser.sql.cnrm.cloud.google.com/sqluser-sample created
```
Update the manifest to:
```
  apiVersion: sql.cnrm.cloud.google.com/v1beta1
  kind: SQLUser
  metadata:
    name: sqluser-sample
  spec:
    instanceRef:
      name: sqluser-dep
    host: "%"
    password:
      value: password
```
Do a server-side dry-run with kubectl:
```
$ kubectl apply --dry-run=server --server-side -f sqluser.yaml
The SQLUser "sqluser-sample" is invalid: 
* <nil>: Invalid value: "": "spec.password" must validate one and only one schema (oneOf). Found none valid
* <nil>: Invalid value: "": "spec.password" must not validate the schema (not)
```
Applying the resource rather than doing a dry-run succeeds:
```
$ kubectl apply -f sqluser.yaml
sqluser.sql.cnrm.cloud.google.com/sqluser-sample configured
```

I will try tomorrow and see if I can figure out why this is happening.
