### ISSUE TITLE
search-and-replace functionConfig should iterate through multiple configs, or allow overwrite

### ISSUE THREAD

**Issue by FrenchBen** [GoogleContainerTools/kpt#2573]
### Expected behavior
When wanting to apply search-and-replace to various resources, you cannot call the function once with various configs. 

### Actual behavior
The function will need to be called for each implementation, of the config. 

### Information
 kpt version: `1.0.0-beta.7`

### Steps to reproduce the behavior

```
# starting data
a:
  b:
  - c: thing0
  - c: thing1
  - c: thing2
```
```
# desired data
a:
  b:
  - c: thing-0
  - c: thing-1
  - c: thing-2
```
---
#### Try replace the entire array

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: search-replace-fn-config-0
data:
  by-path: a.b
  put-value: |
        - c: thing-0
        - c: thing-1
        - c: thing-2
```
(doesn't work)

---
#### Try running multiple configs at once

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: search-replace-fn-config-0
data:
  by-path: a.b[0].c
  put-value: thing-0
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: search-replace-fn-config-1
data:
  by-path: a.b[1].c
  put-value: thing-1
...
```
Run KPT replace: `kpt fn eval --image gcr.io/kpt-fn/search-replace:v0.2 --fn-config fn-replace.yaml `
Error: `error: functionConfig "fn-replace.yaml" must not contain more than one config, got 3`
