### ISSUE TITLE
apply-setters currently skips block scalars

### ISSUE THREAD

**Issue by shaunmitchellve** [GoogleContainerTools/kpt#2641]
Currently the apply-setters function doesn't look at block scalar styles for the kpt-set comments. For example, if you are using the annotation: `config.kubernetes.io/apply-time-mutation:` in KCC then you would pass a string or for erasability a block scalar style string that preserves newlines like `|`:

```yaml
annotations:
  config.kubernetes.io/apply-time-mutation: |
      - sourceRef:
          apiVersion: sql.cnrm.cloud.google.com/v1beta1
          kind: SQLInstance
          name: my-sql-instance# kpt-set: ${sql-instance-name}
          namespace: my-namespace # kpt-set: ${project-id}
        sourcePath: $.status.serviceAccountEmailAddress
        targetPath: $.spec.member
        token: ${sql-sa}
```

However, when running agains the current `gcr.io/kpt-fn/apply-setters:v0.2.0` which would set the name of the SQL instance in resources before this, I'm unable to pass the same name into this block scalar as I'm assuming the render function ignores strings. Having the render function treat block scalars like regular yaml and parse for `kpt-set` setters would help with these types of use-cases.
