### ISSUE TITLE
Function selectors: labels and annotations

### ISSUE THREAD

**Issue by morgante** [GoogleContainerTools/kpt#2756]
### Describe your problem

You should be able to select the resources to apply a function to based on label or annotation.

For example, I might want to set the project ID for all my prod resources to project ID.

```
apiVersion: kpt.dev/v1
kind: Kptfile
metadata:
  name: wordpress
pipeline:
  mutators:
    - image: gcr.io/kpt-fn/set-project-id
      configMap:
        projectId: my-project
      selectors:
        - labels:
            env: prod
```

Or I want to set all "cluster-only" resources (based on annotation) to be set to local-config:

```
apiVersion: kpt.dev/v1
kind: Kptfile
metadata:
  name: wordpress
pipeline:
  mutators:
    - image: gcr.io/kpt-fn/set-annotation
      configMap:
        config.kubernetes.io/local-config: true
      selectors:
        - annotations:
            cnrm.cloud.google.com/ignore-clusterless: true
```
