### ISSUE TITLE
[Question] Migrate kpt 1.0 with execution runtime and network/mount

### ISSUE THREAD

**Issue by PatrickChenSe** [GoogleContainerTools/kpt#2759]
Hi,

We have some questions about kpt1.0 while migrating from 0.39 about `kpt fn` execution runtime. We're using `kpt fn run` with execution runtime and `--network` `--mount`. Function config is like below:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: kpt-fn-1
  annotations:
    config.kubernetes.io/local-config: "true"
    config.k8s.io/function: |
      deferFailure: true
      exec:
        path: 
data: {}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kpt-fn-1
  annotations:
    config.kubernetes.io/local-config: "true"
    config.k8s.io/function: |
      deferFailure: true
      container:
        image:
        network: true
data: {}
``` 
Running the config with
```bash
kpt fn run [dir] --network --enable-exec --mount type=bind,src=[dir],dst=/workdir  --result-dir [dir]
```

I'm glad that kpt1.0 added `execution` runtime for `kpt fn render`, but I found out that `kpt fn render` doesn't support `--network` and `--mount`, they are only supported by `kpt fn eval`. 

So my question is, how can we use `kpt fn` declaratively with `execution runtime` and `network, mount` together in 1.0?
