### ISSUE TITLE
kpt is still checking for CRDs when annotation config.kubernetes.io/local-config: true

### ISSUE THREAD

**Issue by shaunmitchellve** [GoogleContainerTools/kpt#2767]
### Expected behavior

When adding the annotation config.kubernetes.io/local-config: "true" to the resource definition. Kpt would not check to see if the CRD is defined on the server.

### Actual behavior

```
apiVersion: blueprints.cloud.google.com/v1alpha1
kind: ProjectServiceSet
metadata:
  name: gpc-project-services
  namespace: MYNAMESPACE
  annotations:
    cnrm.cloud.google.com/deletion-policy: true
    config.kubernetes.io/local-config: "true"
spec:
  services:
    - cloudapis.googleapis.com
    - clouddebugger.googleapis.com
  projectID: <MY-PROJECT>
```

The above resource uses a kpt function (gcr.io/kpt-fn/enable-gcp-services:v0.1.0) to create other resources (service.serviceusage.cnrm.cloud.google.com) that work perfectly fine.

```
$ kpt live apply

Error: 1 resource types could not be found in the cluster or as CRDs among the applied resources.

Resource types:
ProjectServiceSet.blueprints.cloud.google.com
```

I need to either delete the yaml file or change the extension of that file after `kpt fn render` to get past this error.

### Information
Tried on kpt version: 1.0.0-beta.9 (Google Cloud Shell version)
Also on: 1.0.0-beta.10, 1.0.0-beta.12
