### ISSUE TITLE
`kpt fn render` changes yaml integer to scientific notation 

### ISSUE THREAD

**Issue by yuwenma** [GoogleContainerTools/kpt#2768]
### Describe your problem
input resource:
```yaml
kind: Data
spec:
    ExpirationMs: 3600000
```
Running `kpt fn render` to transform some irrelevant field and do `git diff`
 output resource:
```yaml
kind: Data
spec:
    ExpirationMs: 3.6e+06
```
I want to keep integers' original format and do not change to scientific notation

Similar issue #2487
