### ISSUE TITLE
Add `builtin-gcloud-generator` for variant constructor

### ISSUE THREAD

**Issue by yuwenma** [GoogleContainerTools/kpt#2795]
### Description

related to #2590 

This KRM function is required to be a builtin generator to provide gcloud configuration as context resources (pseudo-resource) to kpt pipeline.

### Implementing details
- GVK. (another option is v1/ConfigMap)
```yaml
apiVersion: kpt.dev/v1
kind: GcloudConfig
metadata:
    name: gcloud-config.kpt.dev
```
- Fields:
```yaml
spec:
    name: <Kptfile Name> 
    namespace:  <PROJECT ID>,
    projectID:  <PROJECT ID>,
    zone: <ZONE>,
    region: <REGION>,
    domain: <domain from user account>,
    orgID: <ORGANIZATION ID>
``` 
- This function requires `Kptfile` passed in in the `resource_list.items` (via flag `--include-meta-resources`) 
- This function is called as an exec in `kpt pkg get` for deployable pkg (` onPkgGet.functions.exec=builtin/generate-gcloud-config`). We can support the image later on (defer to kpt). 
- This function will write to PKG_DIR/GcloudConfig_gcloud-config.kpt.dev.yaml (default file name is ${KIND}_${NAME}), re-run the function will override the same file. 

@droot @bgrant0607  Please confirm.
