### ISSUE TITLE
generate-folders kpt function overly dedupes folders of certain names

### ISSUE THREAD

**Issue by williamjiuchengcai** [GoogleContainerTools/kpt#2817]
Given an example ResourceHierarchy yaml:
```
apiVersion: blueprints.cloud.google.com/v1alpha3
kind: ResourceHierarchy
metadata:
  name: root-hierarchy
  namespace: hierarchy
  annotations:
    cnrm.cloud.google.com/blueprint: cnrm/landing-zone:hierarchy:env-bu/v0.3.0/blueprints_controller
    config.kubernetes.io/local-config: "true"
spec:
  parentRef:
    external: "856213725226"
  subtrees:
    environment:
    - Shared
    - unit a:
      - team i
      - Team-i
  config:
  - Env A:
      $subtree: environment
  - env-a:
      $subtree: environment
```

### Expected behavior
`kpt fn eval` on this YAML generates a hierarchy of folders like: "Env A", "env-a", "Env A/ unit a/ team i", "Env A/ unit a/ Team-i"... etc

### Actual behavior
`kpt fn eval` normalizes to a single "env-a" folder and a single "team-i" folder.

### Information
I believe this behavior is due to the normalization function treating certain delimiters (e.g. dash, space) all as a single type and normalizes it to a "." for kubernetes name. There might be more issues also with the folder YAML naming convention.

Kpt function in question: https://catalog.kpt.dev/

### Steps to reproduce the behavior
Copy the hierarchy YAML from above into a kpt package and run `kpt fn eval -i gcr.io/kpt-fn/generate-folders:v0.1.1`. See the hierarchy generated containing only some expected folders and not all.
