### ISSUE TITLE
kpt live preview/apply results in error: error applying resources: no grouping object found

### ISSUE THREAD

**Issue by govinda-attal** [GoogleContainerTools/kpt#283]
Kpt version: 0.6.0
Kubernetes: GKE v1.13.12-gke.25

I followed the instructions on page: https://googlecontainertools.github.io/kpt/

Expected: Instructions to work as descibed
Got: `error: error applying resources: no grouping object found`

```
$ ./kpt live preview helloworld --stack-trace
error: error applying resources: no grouping object found
```

**Comment by seans3** [comment]
Please note that a `grouping object template` is currently required for `kpt live apply`. An example (shown in the docs) is: 

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-grouping-object
  labels:
    cli-utils.sigs.k8s.io/inventory-id: test-group
```

https://googlecontainertools.github.io/kpt/live/
