### ISSUE TITLE
`kpt pkg update` doing crazy stuff on weird yaml whitespace comments

### ISSUE THREAD

**Issue by julianKatz** [GoogleContainerTools/kpt#2925]
### Expected behavior

`kpt pkg update` would accurately copy the code from the source repository

### Actual behavior

A bunch of whitespace is added.  The whitespace grows with each `kpt pkg update`.

### Information

 `v1.0.0-beta.13`
 https://github.com/open-policy-agent/gatekeeper-library/tree/master/library/general

### Steps to reproduce the behavior

```
kpt pkg update [path to the pkg in your repo] --strategy resource-merge
```

The [actual file](https://github.com/open-policy-agent/gatekeeper-library/blob/master/library/general/httpsonly/template.yaml) looks like this:  

```yaml
apiVersion: templates.gatekeeper.sh/v1
kind: ConstraintTemplate
metadata:
  name: k8shttpsonly
  annotations:
    description: >-
      Requires Ingress resources to be HTTPS only.

      Ingress resources must:
      - include a valid TLS configuration
      - include the `kubernetes.io/ingress.allow-http` annotation, set to
        `false`.

      https://kubernetes.io/docs/concepts/services-networking/ingress/#tls
[more stuff]
```

It appears in our local repository looking this:

```
apiVersion: templates.gatekeeper.sh/v1
kind: ConstraintTemplate
metadata: # kpt-merge: /k8shttpsonly
  name: k8shttpsonly
  annotations:
    description: >-
      Requires Ingress resources to be HTTPS only.

      Ingress resources must: - include a valid TLS configuration - include the `kubernetes.io/ingress.allow-http` annotation, set to



        `false`.

      https://kubernetes.io/docs/concepts/services-networking/ingress/#tls
```

And after another run of `kpt pkg update`:

```
apiVersion: templates.gatekeeper.sh/v1
kind: ConstraintTemplate
metadata: # kpt-merge: /k8shttpsonly
  name: k8shttpsonly
  annotations:
    description: >-
      Requires Ingress resources to be HTTPS only.

      Ingress resources must: - include a valid TLS configuration - include the `kubernetes.io/ingress.allow-http` annotation, set to






        `false`.

      https://kubernetes.io/docs/concepts/services-networking/ingress/#tls
```

And the whitespace gets bigger every time this is run.
