### ISSUE TITLE
`kpt fn render|eval` should support excluding resources from function input

### ISSUE THREAD

**Issue by droot** [GoogleContainerTools/kpt#2930]
## CUJ

`kpt fn render` and `kpt fn eval` supports mechanism to target resources to apply function on.  For example:

```sh
# Apply set-labels on resources of kind Deployment and belonging to group apps
$ kpt fn eval [PKG_DIR] -i set-labals:v0.1.5 --match-group apps --match-kind Deployment 
```

Declaratively, for example, apply `set-labels` on resources with group `apps` and kind `Deployment`.

```yaml
# excerpts from Kptfile

...

pipeline:
  mutators:
   - image: set-labels:v0.1.5
     selectors:
       - group: apps
          kind: Deployment
```

Sometimes users want to exclude set of resources from function's target. For ex. apply this function on all resources except the ones with `kind` `Kptfile` or apply this label on all the deployments except with a specific name.

This will become especially important as we allow `functionConfigs` and `Kptfile` to be included in function input by default in `kpt fn` commands.

## Proposal

Imperative workflow:

```sh
# apply set-labels to all the deployments except a given name
$ kpt fn eval [PKG_DIR] -i set-labels:v0.1.5 --match-kind Deployment --exclude-name some-name

# apply set-labels on resources belonging to apps group except kind StatefulSet
$ kpt fn eval [PKG_DIR] -i set-labels:v0.1.5 --match-group apps --exclude-kind StatefulSet

```

Declarative workflow:

Introduce `exclude` selectors.

```yaml

# apply set-labels on all resources except with kind `Kptfile` or group `apps`
...
pipeline:
  mutators:
   - image: set-labels:v0.1.5
     exclude:
       - kind: Kptfile
       - group: apps

```

Alternatives names for `exclude`: `except`, `reject`

It will also be nice to have a way syntactic sugar for select or exclude all `local-configs` (resources with a `config.kubernetes.io/local-config: "true"` annotation).

**Comment by droot** [comment]
I looked for some prior art in this space and found kustomize's built-in [`replacement` transformer](https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/replacements/#reject) to be the closest.

**Comment by natasha41575** [comment]
@droot Question, when we write something like

```
exclude:
  - kind: Kptfile
  - group: apps
```

Does that mean we should reject resources that have both kind Kptfile and group apps? Or does it mean that we should reject resources that have either kind Kptfile, or group apps?

It seems like it should be the latter, and to do the former it should look like

```
exclude:
  - kind: Kptfile
     group: apps
```

Is that correct?

**Comment by droot** [comment]
It's the latter. It's ORs(ANDs) very similar to how `reject` is implemented. It is also consistent with how `selectors` is implemented.

**Comment by natasha41575** [comment]
From discussion yesterday, `fn eval` exclusions will also be treated as an 'AND', and this should be documented with examples to prevent confusion for users.

This means that something like `--exclude-name some-name --exclude-kind StatefulSet` will exclude resources that have both Kind `StatefulSet` and name `some-name`.

If a user wants to exclude resources that are of either Kind `StatefulSet`, OR name `some-name`, there will be no way to do this with eval, and users will have to do it declaratively with the Kptfile pipeline. 

Some related kustomize issues with similar requests:

Issue to skip PrefixTransformer for certain GVKs: https://github.com/kubernetes-sigs/kustomize/issues/519#issuecomment-527734888

KEP to skip transformations for a specific resource or resource kind: https://github.com/kubernetes/enhancements/pull/1232/files

**Comment by yuwenma** [comment]
Agree with the idea that kpt CLI should be flexible enough to provide a way to select/exclude resources. But I'm not sure if we want to add the feature on function level or even in the pipeline.mutators/validators

Some high level questions I have:
1. What's the right syntax for users to describe the expected hydration workflow (Kptfile specification). Writing the exclusion logic in function level or even the mutator/validator list level is non-trivial user requirements.
2. When we talk about idempotent, should we consider the entire mutation, like changing the function execution order should not end up as different results (this is the criteria for horizontal and resource-specific functions, if kpt pipeline breaks this rule, it would make nested packages hydration error prone)

**Comment by natasha41575** [comment]
Discussed with @droot offline, we are thinking to not support these exclusions right now, and to release the change is and collect feedback from users.

Per @droot's request, I have created an example of how a user would exclude meta resources with the current `selectors` functionality: https://github.com/natasha41575/kpt-exclude-kptfile

The Kptfile looks like this: 

```
apiVersion: kpt.dev/v1
kind: Kptfile
metadata:
  name: example
pipeline:
  mutators:
    - image: gcr.io/kpt-fn/set-labels:unstable
      configPath: functionconfig.yaml
      selectors:
        - apiVersion: "batch/v1"
        - apiVersion: "apps/v1"
        - apiVersion: "v1"
        - apiVersion: "example.com/v1"
```

It's a bit verbose, but it doesn't look too bad to me. Of course verbosity would increase if users have more apiVersions they need to select.
