### ISSUE TITLE
kpt pkg update removes kpt-set from newly added field with empty array

### ISSUE THREAD

**Issue by ursweiss** [GoogleContainerTools/kpt#2960]
### Expected behavior
"kpt pkg update" should keep the setter when the field has an empty array set.

### Actual behavior
If an empty array ([]) is set as value of a new field with a setter, "kpt pkg update" removes the setter comment when adding the new field to the resource.

### Information
Kpt Version:  1.0.0-beta.14

### Steps to reproduce the behavior
**Prepare**
Create a new Kpt pkg which adds two files, one with a working config, where a non-empty value/array is set, and one with an empty value/array (the new field "hostAliases" is commented out for now, as they have to be added during an kpt pkg update in the next step):

```
kpt pkg init

cat << EOF > deploy-ok.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bar
spec:
  selector:
  template:
    spec:
      dummy: bar
      #hostAliases: # kpt-set: \${host-aliases}
      #  - ip: 1.2.3.4
      #    hostnames:
      #      - foo.example.copm
      #      - bar.example.net
EOF

cat << EOF > deploy-nok.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: foo
spec:
  selector:
  template:
    spec:
      dummy: foo
      #hostAliases: [] # kpt-set: \${host-aliases}
EOF
```
Commit the changes and get the Kpt package in another directory.

Then update the package, add the new fields (just uncomment the prepared hostAliases fields) and commit the changes:

```
# Use "sed" on Linux
gsed -i 's/#//' deploy-ok.yaml
gsed -i 's/#//' deploy-nok.yaml
```
Finally, perform an kpt pkg update which adds the new field to both files, but removes the setter from the one with an empty array (deploy-nok.yaml).

```
# dummy-nok.yaml
    spec:
      dummy: foo
      hostAliases: []
---
# dummy-ok.yaml
    spec:
      dummy: bar
      hostAliases: # kpt-set: ${host-aliases}
        - hostnames:
            - foo.example.copm
            - bar.example.net
          ip: 1.2.3.4
```

**Comment by ursweiss** [comment]
Btw. as a workaround for now I set a dummy value in the kpt package and override it with an empty array during render.

```
spec:
  selector:
  template:
    spec:
      dummy: bar
      hostAliases: # kpt-set: ${host-aliases}
        - ip: 192.0.2.1
          hostnames:
            - example.com
```
Both, "example.com" and IP subnet "192.0.2.0/24" (TEST-NET-1) are never used in the real world. So it would not even be needed to override it with an empty value, but I just do it to keep it clean.

Kptfile:

```
...
pipeline:
  mutators:
    - image: gcr.io/kpt-fn/apply-setters:v0.2
      configMap:
        host-aliases: ""
```

After rendering this results in:

```

spec:
  template:
    spec:
      dummy: bar
      hostAliases: [] # kpt-set: ${host-aliases}
```

**Comment by ursweiss** [comment]
Another weird behaviour when handling empty arrays:
```
cat << EOF > deploy-render.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bar
spec:
  selector:
  template:
    spec:
      dummy: bar
      hostAliases: # kpt-set: \${host-aliases}
        - ip: 1.2.3.4
          hostnames:
            - foo.example.copm
            - bar.example.
      securityContext:
        fsGroup: 1000
EOF

cat << EOF >> Kptfile
pipeline:
  mutators:
    - image: gcr.io/kpt-fn/apply-setters:v0.2
      configMap:
        host-aliases: ""
EOF

kpt fn render
```

Results that "hostAliases" is an empty array, which ist correct, but adds the "host-alias" setter to "securityContext":
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bar
spec:
  selector:
  template:
    spec:
      dummy: bar
      hostAliases: [] # kpt-set: ${host-aliases}
      securityContext: # kpt-set: ${host-aliases}
        fsGroup: 1000
```
