### ISSUE TITLE
Can't  set dependencies following the doc

### ISSUE THREAD

**Issue by yuwenma** [GoogleContainerTools/kpt#308]
Reproduce:
1. kpt init an empty folder
```bash
kpt pkg init test8/
ls test8/
Kptfile		README.md
```
2. set dependencies using the example from [the kpt doc](https://googlecontainertools.github.io/kpt/pkg/sync.html) 
```bash
kpt pkg sync set  https://github.com/GoogleContainerTools/kpt.git/package-examples/helloworld-set test8/
Error: failed to read Kptfile -- create one with `kpt pkg init .`: open Kptfile: no such file or directory
```

Modifying the Kptfile with the dependency works.
```yaml
dependencies:
- name: hello-world
  git:
    repo: "https://github.com/GoogleContainerTools/kpt.git"
    directory: "/package-examples/helloworld-set"
    ref: "master"%                     
```
```bash
kpt pkg sync test9/
updating hello-world (test9/hello-world) from master to master
```
