### ISSUE TITLE
`kpt cfg set` mangles untemplated YAML, creates invalid YAML output

### ISSUE THREAD

**Issue by stewartbutler** [GoogleContainerTools/kpt#318]
I'm running into a situation in which I run `kpt cfg set` on a folder and `kpt` produces invalid YAML output.

Minimal test case: [before.zip](https://github.com/GoogleContainerTools/kpt/files/4289980/before.zip)

Unzip and run the following:
```
kpt cfg set testdir gcloud.core.project test1
kpt cfg set testdir gcloud.core.project test2
```

The resulting output for the untemplated file is invalid (full results: [after.zip](https://github.com/GoogleContainerTools/kpt/files/4289988/after.zip)):
```
# Source: istio-discovery/templates/clusterrole-galley-disable-webhook.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: istio-galley-istio-system
  labels:
    release: test-istio
rules:
- apiGroups: # For reading Istio resources
["authentication.istio.io", "config.istio.io", "networking.istio.io", "rbac.istio.io",
    "security.istio.io"]
  resources: ["*"]
...[SNIP]...
```
This minimal example requires two runs of `kpt cfg set`, but I have other cases where a single run is sufficient to generate invalid output. I didn't put one here since it is in a much larger set of configs and I don't have time to isolate the minimum required config to trigger it in a single pass.

I think there are two main issues here:
1) Kpt is producing invalid YAML, apparently due to the way it modifies the location of comments
2) It seems odd that kpt should even *try* to modify a file that has no kpt setter

Let me know if you need further information.

**Comment by pwittrock** [comment]
@phanimarupaka can you take a look?

**Comment by phanimarupaka** [comment]
@pwittrock sure

**Comment by stewartbutler** [comment]
So I just tested after converting a bunch of my setters to the new format, I still hit this bug when `kpt config set` is called multiple times. @phanimarupaka Any news?

**Comment by pwittrock** [comment]
#352

**Comment by pwittrock** [comment]
#353

**Comment by phanimarupaka** [comment]
@stewartbutler We are prioritizing and working on https://github.com/GoogleContainerTools/kpt/issues/352 which will unblock you. You can expect the fix to get in by next release in a week.

**Comment by stewartbutler** [comment]
Excellent, thanks!

**Comment by pwittrock** [comment]
We'll follow up with #353 once #352 is resolved (it is a simpler fix so can unblock you quicker).

Re: #353 -- if I do `kpt cfg cat` on the directory, it doesn't mangle the yaml (besides deleting whitespace between comments which may be a limitation of the yaml parsing library).

**Comment by stewartbutler** [comment]
Trimming whitespace and empty doc separators is fine, the problem seems to happen when comments before an array object are parsed and then re-emitted, since the comments are in-lined with the array and the array indentation is dropped. E.g.

```
key:
  # This is an array
  - ArrayObject1: blah
    Somekey: test
```

becomes:
```
key:
  - # This is an array
ArrayObject1: blah
    Somekey: test
```
after a few passes through kpt.

I sent some additional config examples to @phanimarupaka directly, if you need more examples for testing feel free to email me or drop me a message on gchat.
