### ISSUE TITLE
Cannot unmarshal some ConfigMap values

### ISSUE THREAD

**Issue by tgjonestx** [GoogleContainerTools/kpt#3193]
### Expected behavior
A FunctionConfig defined via an inline configMap should accept values like `"true"` and `"123"` as long as they are explicitly quoted to indicate they are of type `string`. This type of functionality was working with `sigs.k8s.io/kustomize/kyaml v0.13.3`, but something seems to have changed with the introduction of `v0.13.6`

### Actual behavior
The `ResourceList.FunctionConfig.As()` method fails with an error like:
```
unable to convert object to *v1.ConfigMap with error: json: cannot unmarshal [number|bool] into Go struct field ConfigMap.data of type string
```

### Information
Here's my example GO application compiled against ` github.com/GoogleContainerTools/kpt-functions-sdk/go/fn v0.0.0-20220517213353-b99a4025f2aa`:
```
package main

import (
	"fmt"
	"os"

	k8score "k8s.io/api/core/v1"

	"github.com/GoogleContainerTools/kpt-functions-sdk/go/fn"
)

func Run(rl *fn.ResourceList) (bool, error) {
	configMap := &k8score.ConfigMap{}
	if err := rl.FunctionConfig.As(configMap); err != nil {
		rl.Results = append(rl.Results, &fn.Result{
			Severity: fn.Error,
			Message:  fmt.Sprintf("can not get ConfigMap: %s", err),
		})
		return false, err
	}
	rl.Results = append(rl.Results, &fn.Result{
		Severity: fn.Info,
		Message:  fmt.Sprintf("ConfigMap.data[verbose]=%s", configMap.Data["verbose"]),
	})
	rl.Results = append(rl.Results, &fn.Result{
		Severity: fn.Info,
		Message:  fmt.Sprintf("ConfigMap.data[port]=%s", configMap.Data["port"]),
	})

	return false, nil // return false to force output of the Results
}

func main() {
	if err := fn.AsMain(fn.ResourceListProcessorFunc(Run)); err != nil {
		os.Exit(1)
	}
}
```
Here's the Kptfile which produces the error:
```
apiVersion: kpt.dev/v1
kind: Kptfile
metadata:
  name: example
pipeline:
  mutators:
    - image: gcr.io/wpe-cr-dev/kpt-fn-gjones:test
      configMap:
        verbose: "true"
        port: "65"
      # configPath: map.yaml
```

Note that error does not occur, if you replace `configMap` with `configPath` which references a ConfigMap like this:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: example
data:
  verbose: "true"
  port: "65"
```

### Steps to reproduce the behavior

1. Compile the sample app (I used go 1.17.1 on OSX)
2. Run kpt as `kpt fn render --truncate-output=false --output _output --image-pull-policy=ifnotpresent .` using the example Kptfile above (replacing the image name as necesssary)
3. Observe the error message reported above
4. Edit the Kptfile removing the `configMap` entry and enabling `configPath:` which references a ConfigMap file with the same data values
5. Repeat the `kpt fn render` command from (2)
6. Observe that the json unmarshal error is not reported, and the Results include output like:
```
  Results:
    [info]: ConfigMap.data[verbose]=true
    [info]: ConfigMap.data[port]=65
````
