### ISSUE TITLE
Infer setters from substitution pattern

### ISSUE THREAD

**Issue by pwittrock** [GoogleContainerTools/kpt#320]
Currently when creating a substitution, the mapping of markers to setters is explicit:

Command:

```sh
    kpt create-subst hello-world/ image-tag nginx:1.7.9 \
      --pattern IMAGE_SETTER:TAG_SETTER \
      --value IMAGE_SETTER=image \
      --value TAG_SETTER=tag
```

Should be possible with

```sh
    # no values are provided, infer the setters
    kpt create-subst hello-world/ image-tag nginx:1.7.9 --pattern $(image):$(tag)
```

Should be represented in the Kptfile as

```yaml
x-k8s-cli:
  substitution:
    name: image-value
    pattern: $(image):$(tag)
    inferSettersFromPattern: true
```
