### ISSUE TITLE
kpt fn render includes configPath file in output kpt version 1.0.0-beta.15

### ISSUE THREAD

**Issue by thangalang** [GoogleContainerTools/kpt#3204]
### Expected behavior

Running `kpt fn render` should not include the configPath file in its output

Given a package structure like 
```
test/integration/namespace/
├── Kptfile
├── README.md
├── configconnectorcontext.yaml
├── fn-cfg-setters.yaml
├── iam.yaml
└── namespace.yaml
```
and the Kptfile content like so
```
apiVersion: kpt.dev/v1
kind: Kptfile
metadata:
  name: cloudsql-integration-test
info:
  description: packages to run for cloudsql integration test
pipeline:
  mutators:
    - image: gcr.io/kpt-fn/apply-setters:v0.1
      configPath: fn-cfg-setters.yaml
```
where fn-cfg-setter.yaml is the configPath file, running `kpt fn render` should not produce the fn-cfg-setter.yaml in its output directory like so
```
test/integration/namespace/
├── Kptfile
├── README.md
├── configconnectorcontext.yaml
├── iam.yaml
└── namespace.yaml
```

### Actual behavior
Running `kpt fn render` in kpt version 1.0.0-beta.15 keeps the configPath file in its output which `kpt live apply` will try to create as a configMap
```
test/integration/namespace/
├── Kptfile
├── README.md
├── configconnectorcontext.yaml
├── fn-cfg-setters.yaml
├── iam.yaml
└── namespace.yaml
```
### Information

kpt version 1.0.0-beta.15

### Steps to reproduce the behavior
given the following Kptfile
```
apiVersion: kpt.dev/v1
kind: Kptfile
metadata:
  name: cloudsql-integration-test
info:
  description: packages to run for cloudsql integration test
pipeline:
  mutators:
    - image: gcr.io/kpt-fn/apply-setters:v0.1
      configPath: fn-cfg-setters.yaml
```

fn-cfg-setters.yaml
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: fn-config-setters
data:
  test-id: test-01
  project-id: test-02
```
context.yaml
```
apiVersion: core.cnrm.cloud.google.com/v1beta1
kind: ConfigConnectorContext
metadata:
  name: configconnectorcontext.core.cnrm.cloud.google.com
  namespace: test-cloudsql-01 # kpt-set: ${test-id}
spec:
  googleServiceAccount: test-cloudsql-01@some-random-project-id.iam.gserviceaccount.com # kpt-set: ${test-id}@${projec-id}.iam.gserviceaccount.com
```

Run `kpt fn render -o output` with kpt version 1.0.0-beta.15
`tree output`

kpt generated output
```
output
├── Kptfile
├── context.yaml
└── fn-cfg-setters.yaml
```

**Comment by droot** [comment]
@thangalang Thanks for trying out the new release. This change is introduced in beta.15 to treat `functionConfigs` like any other KRM resource. So this is expected.
 
But the good news is that the fix is very simple. Just add `config.kubernetes.io/local-config: "true"` annotation to your `fn-cfgs-setters.yaml` as shown below to indicate that this is a local-config and doesn't need to be applied to the cluster. `kpt live apply` will ignore resources with local-config annotations. You can read the [reference for the `local-config` annotation](https://kpt.dev/reference/annotations/local-config/) to learn more.


```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: fn-config-setters
  annotations:
    config.kubernetes.io/local-config: "true"
data:
  test-id: test-01
  project-id: test-02
```
