### ISSUE TITLE
Support bulk package operations

### ISSUE THREAD

**Issue by mortent** [GoogleContainerTools/kpt#3243]
We want to let users do operations on multiple packages at the same time, i.e. bulk. The most obvious use-case for this is letting users update all downstream packages in one operation.

**Comment by natasha41575** [comment]
@mortent I have some questions about the requirements for this issue.

It seems to follow that if a user does a bulk upgrade, then each downstream package revision affected by the upgrade will get a new `UpdateTask` in their task list, is that correct? 

I see the WoW demo demonstrates updating _all_ downstream packages in one operation. Will we also have to support the use case of updating just _some_ of the downstream packages in one operation?

**Comment by mortent** [comment]
So I think we want to implement this as CRD and controller rather than as a regular API on the aggregated APIserver. So we need to define what the CRD for something like this should look like and keep in mind that we probably need to implement other bulk-like APIs in a similar way.

So I've thought about a few ways we can do this.

```yaml
apiVersion: config.porch.kpt.dev/v1alpha1
kind: BulkPackageUpgrade
metadata:
  name: bulkUpgrade
  namespace: default
spec:
  targetPackages: # must be in the same namespace as the CR
# Option 1: List all packagerevisions (should this be packages instead?) that should be updated explicitly.
    list:
    - my-repo-9626794e984ff13c9a4c64df5af0f15ec3a146bf
    - my-repo-526fa27229adcc3b6a9a544c455c344a3b4d7597
# Option 2: LabelSelector to find the packages that should be updated.
    selector:
      matchLabels:
        package: my-packages
# Option 3: Specify the parent package and all direct downstream packages will be updated.
    parentPackage: my-package #
  targetVersion: v45
status:
  observedGeneration: 4
  conditions:
    ...
  packages:
  - name: my-downstream-package
    status: Updated
    revision: my-repo-526fa27229adcc3b6a9a544c455c344a3b4d7597
```

For the explicit list of packages, I think we can assume that it is up to the client to provide a set of packagerevisions that can actually be updated, but we'll provide feedback to the client through the status subresource. For the other two options, we need to consider which packagerevisions are "eligible" for updates. For example, if the the package `my-package` in the example above has a large number of old packagerevisions, it doesn't seem necessary to upgrade them all. Maybe just the latest packagerevision should be updated (a possible challenge here is that we only consider published packages for the "latest" tag, which means that updating them requires that we create a new packagerevision).

We need to think about how we use package vs packagerevision here. I'm not sure I've gotten it right in this proposal.

And yes, each update of a package will be like doing an update on the individual package, so they will all get the additional update task. The controller should handle that as part of updating each package by calling the current API. At some point we might want to give users the choice of doing an update (with the UpdateTask) or do the reclone-and-replay approach.

Currently we have an example of a controller as part of Porch with the [RemoteRootSync](https://github.com/GoogleContainerTools/kpt/tree/main/porch/controllers). We probably need several controllers for bulk operations and for declarative cluster targeting, so we need to determine how we want to structure this.
