### ISSUE TITLE
kpt fn eval swallow functionConfig in output

### ISSUE THREAD

**Issue by mengqiy** [GoogleContainerTools/kpt#3260]
To reproduce:

```shell
kpt fn eval -o stdout -i gcr.io/kpt-fn/set-labels:v0.1.5 --fn-config /path/to/fn/config.yaml
```

Got:

```yaml
apiVersion: config.kubernetes.io/v1
kind: ResourceList
items:
  ...
```

Expected:

```yaml
apiVersion: config.kubernetes.io/v1
kind: ResourceList
items:
  ...
functionConfig:
  ...
```

This issue exists in the latest kpt release (beta16).
