### ISSUE TITLE
Add ability to specify pipeline function config with selector

### ISSUE THREAD

**Issue by andsens** [GoogleContainerTools/kpt#3304]
Given this config
```
# Kptfile
apiVersion: kpt.dev/v1
kind: Kptfile
metadata:
  name: example
pipeline:
  mutators:
  - image: gcr.io/kpt-fn/apply-replacements:v0.1.1
    configPath: replace.yaml
```

```
# replace.yaml
apiVersion: fn.kpt.dev/v1alpha1
kind: ApplyReplacements
metadata:
  name: replace
  annotations:
    config.kubernetes.io/local-config: "true"
replacements:
- source:
    kind: ConfigMap
    name: some-config
    fieldPath: data.test
  targets:
  - select:
      kind: Deployment
      name: deployment.example
    fieldPaths:
    - metadata.name
```

I would love to see the ability to reference the function config like this instead:
```
[...]
  mutators:
  - image: gcr.io/kpt-fn/apply-replacements:v0.1.1
    configSelector:
      # No "kind" selector necessary since it's always "ApplyReplacements"
      name: replace
```

This changes carries with it quite a few advantages:

* You are no longer limited to specifying one config per file. Configs that belong together semantically can reside in the same file.
* Preceeding pipeline functions can actually *generate* configs for subsequent functions since we don't reference a specific file that must exist from the get-go.
* It seems to be more in line with how the rest of kpt works, where filepaths and files themselves are just metadata during processing.
* If preprocessing ever becomes a thing, a child package could change how a parent package behaves, allowing for more concise setups

The disadvantage I see is mostly the introduction of footguns:

* You no longer have the WYSIWYG guarantee for function configs: When debugging you'll always have to keep in mind that a bug *might* be caused by an inadvertent config change (though the configs are all their own kind, so it might not be that likely to happen unless using completely unguarded mutations)
* Finding a function config is not as direct. If you're unfamiliar with the package you'll spend time searching through it to find the referenced config.
