### ISSUE TITLE
In porch: kpt-merge directive missing in downstream packages

### ISSUE THREAD

**Issue by droot** [GoogleContainerTools/kpt#3307]
### Expected behavior

In porch, when I create a downstream package using `clone` operation,  I expect `# kpt-merge:` directive to be added to the resources in downstream package. This is required for updating the downstream package in future to reconcile identity of downstream resources with upstream ones. An example of downstream resource:

```yaml
apiVersion: v1
kind: ResourceQuota
metadata: # kpt-merge: example/default
  name: default
  namespace: backend
spec:
  hard:
    cpu: "40"
    memory: 40G
```

### Actual behavior

`# kpt-merge` directive is missing. Quick look at the code in porch suggests, `addmergecomment.AddMergeComment` is not being applied after fetching the downstream resources.

### Steps to reproduce the behavior

```sh

$ kpt alpha rpkg clone <upstream-pkg> backend-1 --repository <deployment-repo> -n default

$ kpt alpha rpkg pull <downstream/pkg/with/name/backend-1> -n default

# resources don't have `kpt-merge` directive.
```

Sidenote: I think storing original identity of the resource in annotation might be better to foolproof it because comments are more likely to get dropped in the transport (or serialization/deserialization).
