### ISSUE TITLE
`kpt pkg update` overwrites updateStrategy

### ISSUE THREAD

**Issue by andsens** [GoogleContainerTools/kpt#3308]
A folder named `upstream` containing the following `Kptfile` is updated with `kpt pkg update upstream`.  
`upstream/Kptfile`:  
```
apiVersion: kpt.dev/v1
kind: Kptfile
metadata:
  name: traefik
  annotations:
    config.kubernetes.io/local-config: "true"
upstream:
  type: git
  git:
    repo: git@github.com:orbit-online/kpt-packages
    directory: /traefik
    ref: master
  updateStrategy: force-delete-replace
upstreamLock:
  type: git
  git:
    repo: git@github.com:orbit-online/kpt-packages
    directory: /traefik
    ref: master
    commit: 8122b57e4662622e9d4f3e47612b937a465fa222
```

```
$ kpt pkg update upstream
Package "upstream":
Fetching upstream from git@github.com:orbit-online/kpt-packages@master
From github.com:orbit-online/kpt-packages
 * branch            master     -> FETCH_HEAD
Updating package "upstream" with strategy "resource-merge".

Updated 1 package(s).
```

### Expected behavior

I expect kpt to overwrite all existing content in `upstream/` with the exception of the upstream config itself:  
```
apiVersion: kpt.dev/v1
kind: Kptfile
metadata:
  name: traefik
  annotations:
    config.kubernetes.io/local-config: "true"
upstream:
  type: git
  git:
    repo: git@github.com:orbit-online/kpt-packages
    directory: /traefik
    ref: master
  updateStrategy: force-delete-replace
upstreamLock:
  type: git
  git:
    repo: git@github.com:orbit-online/kpt-packages
    directory: /traefik
    ref: master
    commit: 63c5c19be832769e20dee4d6bb474b6de8191331
```

### Actual behavior

`kpt` uses the `resource-merge` strategy to update `upstream/` and overwrites the strategy in the `Kptfile`
```
apiVersion: kpt.dev/v1
kind: Kptfile
metadata:
  name: traefik
  annotations:
    config.kubernetes.io/local-config: "true"
upstream:
  type: git
  git:
    repo: git@github.com:orbit-online/kpt-packages
    directory: /traefik
    ref: master
  updateStrategy: force-delete-replace
upstreamLock:
  type: git
  git:
    repo: git@github.com:orbit-online/kpt-packages
    directory: /traefik
    ref: master
    commit: 63c5c19be832769e20dee4d6bb474b6de8191331
```

### Information

I'm not really sure what the point of the `updateStrategy` property in the Kptfile is, if not to configure how the upstream should be updated (hence the `bug` label). My current workaround is specifying `--strategy force-delete-replace` everytime I update an upstream package.

### Steps to reproduce the behavior

1. Create an upstream kpt package
2. Create a kpt package that depends on the upstream package and specify `updateStrategy` as `force-delete-replace`
3. Update the second kpt package with `kpt pkg update <path>`

**Comment by droot** [comment]
This definitely looks like a bug. Thanks for reporting it @andsens

**Comment by yuwenma** [comment]
@andsens I think the confusion is that kpt uses `upstream` field as `status` (track the referred upstream), but you'd expect it to be a `spec` (configure the `upstream` field to change the behavior of `kpt pkg update`).

Considering the `pipeline` field is used a configurations. I think we should distinguish the `spec` and `status` in Kptfile, like most k8s resources. 

Something like below may mitigate similar confusions.

```
kind: Kptfile
spec:
     pipeline: .... 
status:
     upstream:
     upstreamLock:...
```
