### ISSUE TITLE
Support enabling network access when using `kpt fn run --image`

### ISSUE THREAD

**Issue by dflemstr** [GoogleContainerTools/kpt#334]
Since there is no place to declare function behavior in this situation, I would suggest supporting a command-line flag for enabling access.

Maybe we could trust `--network` ultimately in case `--image` is already set?

**Comment by pwittrock** [comment]
@phanimarupaka I think this may already be supported, would you confirm?

**Comment by phanimarupaka** [comment]
@dflemstr This feature is already supported in kpt. You can find the usage by running "kpt fn run -h" and scroll though flags section.

**Comment by dflemstr** [comment]
Thanks for getting back to me!  I saw the flags in that section, but despite that I keep getting errors.

Some examples:

```shell
# A simple kpt function that simply pipes objects to kubeval
$ kpt fn run --network --image gcr.io/spotify-declarative-infra/kubeval
ERR  - stdin: Failed initalizing schema https://...: Get https://...: dial tcp: lookup kubernetesjsonschema.dev on 1.1.1.1:53: dial udp 1.1.1.1:53: connect: network is unreachable
```

However, running the exact same function with this config works:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: kpt-fn-2
  annotations:
    config.k8s.io/function: |
      container:
        image: gcr.io/spotify-declarative-infra/kubeval
        network:
          required: true
```

The image is private, let me know if I should create a test case that can be reproduced publicly.
