### ISSUE TITLE
kpt-set mark removed from line after update to 1.0.0-beta.18

### ISSUE THREAD

**Issue by RafalMaleska** [GoogleContainerTools/kpt#3405]
### Expected behavior

`kpt pkg update`
 
```
apiVersion: v1
kind: Namespace
metadata: # kpt-merge: /some-app
  name: some-app # kpt-set: ${some-app}
  labels:
  annotations:
    ncp/static_snat_ip: 122.122.122.122 # kpt-set: ${gateway-snat-ip}
```

### Actual behavior

`kpt pkg update`

```
apiVersion: v1
kind: Namespace
metadata: # kpt-merge: /some-app
  name: some-app # kpt-set: ${some-app}
  labels:
  annotations:
    internal.kpt.dev/upstream-identifier: '|Namespace|default|some-app'
    ncp/static_snat_ip: 122.122.122.122
```

### Information

kpt version: 1.0.0-beta.18

After updating kpt to the newest version and using `kpt pkg update` a new annotation is added (as stated in the release notes). For some reason if there is another annotation which needs to be modified by a kpt function (kpt-set). The function mark is removed and the pipeline is ignoring this resource. 

Briefly: 

- before update the last line looked after kpt pkg update like: 
```
    ncp/static_snat_ip: 122.122.122.122 # kpt-set: ${gateway-snat-ip}
```
- after update to the newest version the last line is missing the # kpt-set

```
    ncp/static_snat_ip: 122.122.122.122 
```

Is it possible to not use the new kpt annotation? 
Is it a bug of kpt which causes the removal of this kpt-set mark?

### Steps to reproduce the behavior

kpt pkg update on an upstream resource which has an kpt-set function on an annotation. Tested this only with the namespace resource.

**Comment by mortent** [comment]
This is probably related to https://github.com/GoogleContainerTools/kpt/pull/3360.
@yuwenma

**Comment by yuwenma** [comment]
Thanks for reporting this! I'll take a look today.

**Comment by yuwenma** [comment]
@RafalMaleska The fix should go in soon. 
Just a suggestion about your `ncp/static_snat_ip` annotation, `set-labels` is a preferred function than setters. 
You can try something like
```yaml
# Kptfile
pipeline:
    mutators:
         - image: gcr.io/kpt-fn/set-labels:v0.1.5
            configMap:
                 ncp/static_snat_ip: "122.122.122.122"
```
Or 
```yaml
# Kptfile
pipeline:
    mutators:
         - image: gcr.io/kpt-fn/set-labels:v0.1.5
            configPath: fnconfig.yaml
# fnconfig.yaml
apiVersion: v1
Kind: ConfigMap
metadata:
   ...
data:
   ncp/static_snat_ip: "122.122.122.122"
```
 See https://catalog.kpt.dev/set-labels/v0.1/

**Comment by RafalMaleska** [comment]
@yuwenma thank you for clarification and the upcoming fix


I've tried your suggestion. It works, but only for labels :) 
The reported issue was with annotations. 

Side Info: We're using the Kptfile like a central values file where a user can set all required values (with ca. 50 possible values mutating ca. 600 fields). Therefore the setters function plays handy with our setup because it allows us to avoid using additional fn-configmaps.

**Comment by yuwenma** [comment]
> @yuwenma thank you for clarification and the upcoming fix
> 
> I've tried your suggestion. It works, but only for labels :) The reported issue was with annotations.

(Typo 😵‍💫 since I'm working on a label KRM function these days)

set-annotation function is very similar

# Kptfile
pipeline:
    mutators:
         - image: gcr.io/kpt-fn/set-annotations:v0.1.4
            configMap:
                 ncp/static_snat_ip: "122.122.122.122"
```
Or 
```yaml
# Kptfile
pipeline:
    mutators:
         - image: gcr.io/kpt-fn/set-annotations:v0.1.4
            configPath: fnconfig.yaml
# fnconfig.yaml
apiVersion: v1
Kind: ConfigMap
metadata:
   ...
data:
   ncp/static_snat_ip: "122.122.122.122"
```
 See https://catalog.kpt.dev/set-annotations/v0.1/

> 
> Side Info: We're using the Kptfile like a central values file where a user can set all required values (with ca. 50 possible values mutating ca. 600 fields). Therefore the setters function plays handy with our setup because it allows us to avoid using additional fn-configmaps.

Do you mean the "handy" apply-setter is due to the single configuration file(setters.yaml or configmap)?  Considering the 50 values and 600 fields, I'd assume it would require a lot of human efforts (especially for the team who setup the setters.yaml config files) to make sure the value fields are not cross passing, no mis configurations, etc.
