### ISSUE TITLE
kpt function catalog docs should include `config.kubernetes.io/local-config: "true"` annotation wherever function config is referred.

### ISSUE THREAD

**Issue by droot** [GoogleContainerTools/kpt#3409]
kpt treats functionConfigs like any other resource. FunctionConfigs need to be marked `loca-config` so that they are not applied to cluster.

kpt function catalog docs (and examples) should include `config.kubernetes.io/local-config: "true"` annotation wherever function config is referred.

```yaml
metadata:  
  annotations:
    config.kubernetes.io/local-config: "true"
```
