### ISSUE TITLE
Cannot render kpt package with batch/v1 Jobs using `metadata.generateName`

### ISSUE THREAD

**Issue by zevisert** [GoogleContainerTools/kpt#3573]
### Expected behavior

I can `kpt fn render` a package containing a Job that uses `metadata.generateName`  instead of `metadata.name` using curated functions from catalog.kpt.dev. 

### Actual behavior

```console
> kpt fn render aheqox
Package "aheqox": 
[RUNNING] "set-namespace:v0.4.1"
[FAIL] "set-namespace:v0.4.1" in 0s
Error: input resource list must contain only KRM resources: image-migration.job.yaml: resource must have `metadata.name` 
```

### Information

I have a job that performs some migrations tasks that is to be run once immediately after deployment. Since deployments may occur one-after-another in quick succession, setting `spec.ttlSecondsAfterFinished` is insufficient, since the spec of the job being deployed gets changed with each deployment, leading to 

```console
> kpt live apply # using metadata.name on my job
Resource: "batch/v1, Resource=jobs", GroupVersionKind: "batch/v1, Kind=Job"
Name: "image-migration", Namespace: "project-aheqox"
for: "some.job.yaml": Job.batch "migrate-tasks" is invalid: spec.template: Invalid value: ...
```

```console
> kpt version 
1.0.0-beta.13
```

### Steps to reproduce the behavior

1. Create these files: 

```yaml
# ./Kptfile
apiVersion: kpt.dev/v1
kind: Kptfile
metadata:
  name: aheqox
  annotations:
    config.kubernetes.io/local-config: "true"
info:
  description: A KPT package demonstrating an issue with generateName.
pipeline:
  mutators:
    - image: set-namespace:v0.4.1
      configMap:
        namespace: project-aheqox
    - image: apply-setters:v0.2.0
      configMap:
        # Not fully relevant, but here to demonstrate that the job `.spec.template` may be changing,
        # which prevents using a metadata.name in our use case.
        new-name: example1 
```

```yaml
# ./some.job.yaml
apiVersion: batch/v1
kind: Job
metadata:
  generateName: migrate-tasks-
spec:
  ttlSecondsAfterFinished: 3600
  template:
    spec:
      containers:
        - name: example # kpt-set: ${new-name}
          image: hello-world
```

2. Run `kpt fn render .`
