### ISSUE TITLE
use kustomize replacement-style path splitting in `set-image`'s `additionalImageFields`

### ISSUE THREAD

**Issue by zevisert** [GoogleContainerTools/kpt#3580]
### Describe your problem

A lot of the same motivation from replacements in kustomize would be useful in `set-image`'s `additionalImageFields.path`. 

We have `additionalImageFields` to handle CRDs, but we don't support filtering in sequences, take this made-up-resource for example:

```yaml
apiVersion: example.dev/unreleased
kind: InstanceList
metadata:
  name: my-instances
spec:
  instances:
    - name: instance1
      image: example.dev/image:alpha
    - name: instance2
      image: example.dev/image:alpha
```

Say I want to use `kpt` to change `example.dev/image:alpha` to `docker.io/library/hello-world:latest`, my options with this resource in the kpt toolchain are `apply-setters`, or `search-replace`, but really it should be done with `set-image`. 

Using `set-image` it seems like it's only possible to process each item in the sequence because set-image uses [sigs.k8s.io/kustomize/api@v0.11.0/filters/imagetag.Filter](https://pkg.go.dev/sigs.k8s.io/kustomize/api@v0.11.0/filters/imagetag?utm_source=gopls#Filter), which only supports syntax like `spec/instances[]/image`, but in cases like this I actually need the kustomize [replacement-style](https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/replacements/#field-path-format) filters, like `spec.instances.[name=instance1].image` implemented here [sigs.k8s.io/kustomize/api@v0.11.0/internal/utils#SmarterPathSplitter](https://pkg.go.dev/sigs.k8s.io/kustomize/api@v0.11.0/internal/utils#SmarterPathSplitter).
