### ISSUE TITLE
kpt-fn: set-namepsace skipping resources

### ISSUE THREAD

**Issue by shaunmitchellve** [GoogleContainerTools/kpt#3588]
### Expected behavior
Kptfile.yaml
```
apiVersion: kpt.dev/v1
kind: Kptfile
metadata:
  name: test-kpt
pipeline:
  mutators:
    - image: gcr.io/kpt-fn/set-namespace:v0.4.1
      configMap:
        namespace: dev-mynamespace
```
Target yaml file
```
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: backend-config
spec:
  healthCheck:
    port: 8080
    requestPath: /docs
```
Running
`kpt fn render`
should generate
```
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: backend-config
  namepsace: dev-mynamespace
spec:
  healthCheck:
    port: 8080
    requestPath: /docs
```
### Actual behavior
The target yaml file is not update.

I think this is due to the fact that the  apiVersion being `cloud.google.com/v1` which is does not match any of the case statements in `visitNamespaces` function in the `transformer/namespace.go` file.
### Information

kpt version - 1.0.0-beta.15
set-namespace version - 0.4.1
