### ISSUE TITLE
Add selector functionality to set-namespace

### ISSUE THREAD

**Issue by wmuizelaar** [GoogleContainerTools/kpt#3617]
### Describe your problem

We want to run `set-namespace` against KCC based resources. If we for example provide this input yaml:

```
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: example
  namespace: example-namespace
spec:
  resourceRef:
    apiVersion: iam.cnrm.cloud.google.com/v1beta1
    kind: IAMServiceAccount
    name: example
    namespace: example-namespace
  role: roles/iam.workloadIdentityUser
  member: serviceAccount:example-project.svc.id.goog[example-namespace/example]
```

And let `set-namespace` run on this, only the first `metadata.namespace` field is replaced with the desired value. It would be nice if we could provide some configuration to also update the namespace in the `spec.resourceRef.namespace` field. Now we have to do it with `apply-replacements`, and target it that way, but it would be more convenient if `set-namespace` will all fix this in 1 go.
