### ISSUE TITLE
Add index based file path select in apply-replacements function

### ISSUE THREAD

**Issue by efistasija** [GoogleContainerTools/kpt#3629]
### Describe your problem
According to the apply-replacements function documentation, [`The syntax for replacements is described in the [kustomize replacements](https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/replacements/) docs.` ](https://catalog.kpt.dev/apply-replacements/v0.1/)
According to the kustomize docs, file path select on nodes can be done in 3 ways (https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/replacements/#field-path-format):
1. Index by number: spec.template.spec.containers.1.image
2. Index by key-value pair: spec.template.spec.containers.[name=nginx].image. If the key-value pair matches multiple elements in the sequence node, all matching elements will be targetted.
3. Index with a wildcard match: spec.template.spec.containers.*.env.[name=TARGET_ENV].value. This will target every element in the list.

When trying to use the index by number field selector in the apply-replacements, I get the following error when running `kpt fn render .`:
`    [error]: error finding field in replacement target: list path element must contain fieldName=fieldValue for element to match
`
This is an example apply-replacements yaml file I am using:

```
apiVersion: fn.kpt.dev/v1alpha1
kind: ApplyReplacements
metadata:
  name: deployment-replacements
  annotations:
    config.kubernetes.io/local-config: "true"
replacements:
  - source:
      kind: Kptfile
      fieldPath: metadata.name
    targets:
      - select:
          kind: Ingress
        fieldPaths:
          - spec.tls.[0].hosts.[0]
```
### Feature request
Provide index based node field selection in the apply-replacements function.
