### ISSUE TITLE
[Feature Request] Kpt fn apply-setters: add option to surround the final field with single/double quotes

### ISSUE THREAD

**Issue by zhaohua-jiang** [GoogleContainerTools/kpt#3673]
### Describe your problem

consider following cases:

### **we'd like to set `spec.template.metadata.labels` as**

```
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/version: xxxxxxx # kpt-set: ${APP_VERSION}
        ...
```

here, **_APP_VERSION_** would be in the format of 7 digit of  abbreviated git revision(hash), and the setter config map is:

```
apiVersion: v1
data:
  APP_VERSION: "0071335"
kind: ConfigMap
metadata: # kpt-merge: example/setters.dev
  annotations:
    internal.kpt.dev/upstream-identifier: '|ConfigMap|example|setters.dev'
  name: setters.dev
  namespace: default
```
however, when the git revision is all digit, e.g.: 0071335,
even the `APP_VERSION` in the setter config map is surrounded with '",  the final generated k8s file would like:

```
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/version: 0071335 # kpt-set: ${APP_VERSION}
```
the `0071335` doesn't have the expected '"' surrounded, apply the generated k8s manifest yields error like:

```
KNV1067: failed to encode declared fields: .spec.template.metadata.labels.app.kubernetes.io/version: expected string, got &value.valueUnstructured{Value:29405}
```

if we have an opportunity to inform the `kpt-set` to surround the generate field values with single/double quotes, then,
things could be solved perfectly

```
# we could use some syntax for `kpt-set` like:
app.kubernetes.io/version: xxxxxxx # kpt-set: \"${APP_VERSION}\"

# or, to make it simple and clear, maybe we could introduce specific `kpt-set-str`: 
app.kubernetes.io/version: xxxxxxx # kpt-set-str: ${APP_VERSION}
```

### another case is when declaring pod environments, as all environment value shall be in type `string`

then following snippet won't work if `ENV_SHARD` in the setter are string of all digits.

```
      - env:
        - name: SHARD_NUMBER
          value: "xyz" # kpt-set: ${ENV_SHARD}
```

the k8s content after `kpt fn render` will be something like:

```
      - env:
        - name: SHARD_NUMBER
          value: 12 # kpt-set: ${ENV_SHARD}
```
OOPS, apply the generate manifests will lead to error as it's in type `Integer`, not required `String`.

---

I had tried different combination for kpt-set in latest release `1.0.0-beta.23`: 

```
# case 1: if we use kpt-set: '${APP_VERSION}'
output => app.kubernetes.io/version: '''0071335''' # kpt-set: '${APP_VERSION}'

# case 2: if we use kpt-set: "${APP_VERSIONI}"
output => app.kubernetes.io/version: '"0071335"' # kpt-set: "${APP_VERSION}"

# case 3: if we use kpt-set: \"${APP_VERSION}\"
output => app.kubernetes.io/version: '\"0071335\"' # kpt-set: \"${APP_VERSION}\"
```

I just want `app.kubernetes.io/version: "0071335"`  , it’s so hard :face_palm:
