### ISSUE TITLE
kpt fn render results permission problem while running within bitbucket pipeline

### ISSUE THREAD

**Issue by cezhang** [GoogleContainerTools/kpt#3765]
### Expected behavior
`kpt fn render` will succeed
### Actual behavior
```
kpt fn render
Package "deployment": 
[RUNNING] "[gcr.io/kpt-fn/set-image:v0.1.1](http://gcr.io/kpt-fn/set-image:v0.1.1)"
[FAIL] "[gcr.io/kpt-fn/set-image:v0.1.1](http://gcr.io/kpt-fn/set-image:v0.1.1)" in 0s
  Stderr:
    "docker: Error response from daemon: authorization denied by plugin pipelines: --security-opt is not allowed."
    "See 'docker run --help'."
  Exit code: 125
````

### Information
Env: bitbucket pipeline
Install method: go install 
Seems it does't allow docker to using `--mount` because of security reason
Ref: https://confluence.atlassian.com/bbkb/docker-error-authorization-denied-by-plugin-pipelines-command-not-supported-1142238807.html

Any workaround? 

### Steps to reproduce the behavior

**Comment by droot** [comment]
Interesting thing is kpt is invoking docker with `--security-opt=no-new-privileges` stating run the docker runtime without granting any additional new privileges. Right thing for `bitbucket` would have been allowing certain values for `--security-opt` arg.

Unfortunately, this argument is added by default so no workaround at the moment.

**Comment by cezhang** [comment]
I came across a very nasty temporary solution(very un-recommended, also contradict my intention to try this tool).

Since I just want to update my image version:
```
- |
  cat << EOF > tmp
  apiVersion: config.kubernetes.io/v1
  kind: ResourceList
  items:
  - 
  $(sed 's/^/  /g' *deployment.yaml)
  functionConfig:
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: labels
    data:
      name: xxxx
      newName: xxxx
      newTag: xxxx
  EOF
- docker run --rm -i gcr.io/kpt-fn/set-image:v0.1.1 < tmp | yq ".items[0]" > $(find . -name "*deployment.yaml")
```
Actually I construct kpt cli pipeline manually, anyway, hope the community will cover this support.
