### ISSUE TITLE
error: json: unsupported type: map[interface {}]interface {}

### ISSUE THREAD

**Issue by remeq** [GoogleContainerTools/kpt#3897]
Hi,

I am trying to apply my kpt package and getting errror `error: json: unsupported type: map[interface {}]interface {}` for some of my manifests. For example I am getting this for following manifest: https://github.com/knative/eventing/releases/download/knative-v1.9.7/eventing-crds.yaml

I am using kpt 1.0.0-beta.29

Regards,
Premek

**Comment by yuwenma** [comment]
Thanks for filing the issue @remeq  

I think the issue is that `kpt live apply` cannot support merging arrays in YAML. 

In the CRD yaml file, the `CustomResourceDefinition` ` pingsources.sources.knative.dev` has the following lines that triggers the problem
 
```yaml
spec:
  group: sources.knative.dev
  versions:
    - &version # HERE
      name: v1beta2
      served: true
      storage: false
      ... (IGNORED)
    - !!merge <<: *version # HERE
      name: v1
      served: true
      storage: true
```

@mortent This seems to be a nice feature to add to `kpt live`. I'm thinking of marking this as "first good issue", WDYT?
