### ISSUE TITLE
Kptfile pipelines should support mount and network flags

### ISSUE THREAD

**Issue by uv-Ic** [GoogleContainerTools/kpt#3924]
### Describe your problem

I'm trying to use kpt pipeline with render-helm-chart function as mutator.
In order to use local or remote chart we need to pass one of the following flags to docker which the Kptfile doesn't support:
* mount
* network

(In some cases the `as-current-user` flag is required as well.)

Current mitigation is to use exec mutator and run a script with the required flags, for example:
snippet from kptfile
```
pipeline:
  mutators:
    - exec: ./render_command.sh
  validators:
    - image: gcr.io/kpt-fn/kubeval:v0.1
```

render_command.sh
```
#!/bin/bash
kpt  fn eval  \
  --image gcr.io/kpt-fn/render-helm-chart:unstable \
  --mount type=bind,src=$(pwd),dst=/tmp/charts \
  --as-current-user \
  --truncate-output=false \
  --results-dir /tmp/result \
  -- name=spanner-chart releaseName=test
```

It would be useful if we can pass these flags in the Kptfile like that:
```
pipeline:
  mutators:
    - image: gcr.io/kpt-fn/render-helm-chart:unstable
      mount: 
         type: bind
         src: .
         dst: /tmp/charts
      as-current-user: true
      configMap:
         name: spanner-chart
         releaseName: test
```
