### ISSUE TITLE
kpt not preserving comment only objects

### ISSUE THREAD

**Issue by nduja** [GoogleContainerTools/kpt#3941]
### Expected behavior

`kpt fn eval` preserves all comments  in a yam file.

### Actual behavior

`kpt fn eval` removes objects/documents made up of only comments.

### Information

kpt version: 1.0.0-beta.31

In our packages we use these "comment only" objects for headers/context for humans and would like to preserve them

### Steps to reproduce the behavior

1. Create a yaml file with an object of entirely comments.
    ```
    # Comment only object
    ---
    # Comment in object
    apiVersion: v1
    kind: Namespace
    metadata:
      name: test-ns
    ```
1. Run a `kpt fn eval` function
    `kpt fn eval --image gcr.io/kpt-fn/search-replace:v0.2.0 --exclude-kind 'Namespace' -- 'by-path=metadata.name' "put-value=test-ns"`
1. Inspect file, "# Comment only object" is removed.
    ```
    $ cat ns.yaml 
    # Comment in object
    apiVersion: v1
    kind: Namespace
    metadata:
      name: test-ns
    ```
