### ISSUE TITLE
Reference Substrings in Apply Time Mutations

### ISSUE THREAD

**Issue by tylerreidwaze** [GoogleContainerTools/kpt#3966]
### Describe your problem

I  am trying to create a Memcached Instance and a DNS Entry for that instance in a single package

I'm trying to use apply-time-mutation which will get the discoveryEndpoint of the memcached and create a DNS record for it in DNS.

The problem is the result includes the port:

```
kubectl get MemcacheInstance memcached-kpt-test -o jsonpath='{.status.discoveryEndpoint}'
10.19.208.3:11211
```

And I can't find a way to split it as jsonPath doesnt let me index strings (strings aren't arrays I suppose?)

```
> kubectl get MemcacheInstance memcached-kpt-test -o jsonpath='{.status.discoveryEndpoint[0:-6]}' -n waze-platform-codelabs
error: error executing jsonpath "{.status.discoveryEndpoint[0:-6]}": Error executing template: string is not array or slice. Printing more information for debugging the template:
	template was:
		{.status.discoveryEndpoint[0:-6]}
```

The whole object we tried as reference
```
metadata:
  name: memcached-kpt-test
  annotations:
    config.kubernetes.io/apply-time-mutation: |
      - sourceRef:
          kind: MemcacheInstance
          name: memcached-kpt-test
        sourcePath: $.status.discoveryEndpoint[0:10]
        targetPath: $.spec.rrdatas.value
        token: ${memcache-discovery-ip}
spec:
  name: "memcached-kpt-test.dretest."
  type: "A"
  ttl: 60
  managedZoneRef:
    external: dretest
  rrdatas:
  - "${memcache-discovery-ip}"
```

This is not a massive blocker for us as Apply Time Mutations aren't supported yet in Config Sync which is the eventual consumer of this output.

Let us know if you need more information or want us to test something out.  Or, if there is a more kpt native way to do this.

Thanks in advance!
