### ISSUE TITLE
Create Setters don't work for arrays

### ISSUE THREAD

**Issue by wonderflow** [GoogleContainerTools/kpt#469]
My yaml is like below, I have an array of containers and I want to make container image as a setter.

```
apiVersion: core.oam.dev/v1alpha2
kind: Component
metadata:
  name: example-component
spec:
  workload:
    apiVersion: core.oam.dev/v1alpha2
    kind: ContainerizedWorkload
    spec:
      containers:
        - name: my-nginx
          image: nginx:1.16.1
          resources:
            limits:
              memory: "200Mi"
          ports:
            - containerPort: 4848
              protocol: "TCP"
          env:
            - name: WORDPRESS_DB_PASSWORD
              value: ""
```

I create a setter by using following command:

```
$ kpt cfg create-setter sampleapp/ image nginx:1.16.1 --field "spec.workload.spec.containers[0].image" --description "use to set image for component" --set-by "sampleapp developer"
```

But it didn't work when I try to set this setter:

```
$ kpt cfg set sampleapp/ image nginx:latest
set 0 fields
```

Nothing changed to my container image.
