### ISSUE TITLE
Kpt pkg init: load the upstream info if the package is in gitops

### ISSUE THREAD

**Issue by nan-yu** [GoogleContainerTools/kpt#474]
I have a package pushed up to a git repo and would like to run `kpt pkg diff` against it.
Kpt requires to have a Kptfile under the package, so I did `kpt pkg init my-pkg`. However, `kpt pkg diff` still failed because of `Error: must specify repo`.

What I ended up doing is to delete my package locally, and then use `kpt pkg get git@..../my-pkg` to get the package and Kptfile.
```
$ kpt pkg diff my-pkg
Error: must specify repo

$ rm -rf my-pkg
$ kpt pkg get git@github.com:nan-yu/my-repo.git/my-pkg .
```

I was thinking `kpt pkg init` could automatically load the `upstream` info if the package is in git.
Instead of a simple initial Kptfile:
```
apiVersion: kpt.dev/v1alpha1
kind: Kptfile
metadata:
  name: my-pkg
packageMetadata:
  shortDescription: sample description
```

It should include the `upstream` section:
```
apiVersion: kpt.dev/v1alpha1
kind: Kptfile
metadata:
    name: my-pkg
upstream:
    type: git
    git:
        commit: 98c819b489a1aa93ce063264445ad97485592021
        repo: git@github.com:nan-yu/my-repo
        directory: /my-pkg
        ref: master
```
