### ISSUE TITLE
 kpt live apply can't recognise some CRD

### ISSUE THREAD

**Issue by wonderflow** [GoogleContainerTools/kpt#498]
I have some CRDs in my K8s cluster.

* manualscalertraits.core.oam.dev
* applicationconfigurations.core.oam.dev
* components.core.oam.dev
* traitdefinitions.core.oam.dev
* workloaddefinition.core.oam.dev

When I want to apply CR of these CRD and install it with `kpt live apply`, I got this output:

```
configmap/grouping-object-a4e18a93 unchanged
applicationconfiguration.core.oam.dev/example-appconfig unchanged
component.core.oam.dev/test-component unchanged
traitdefinition.core.oam.dev/manualscalertraits.core.oam.dev unchanged
workloaddefinition.core.oam.dev/containerizedworkloads.core.oam.dev unchanged
5 resource(s) applied. 0 created, 5 unchanged, 0 configured
configmap/grouping-object-a4e18a93 is Current: Resource is always ready
applicationconfiguration.core.oam.dev/example-appconfig is Current: Resource is current
component.core.oam.dev/test-component is Current: Resource is current
traitdefinition.core.oam.dev/manualscalertraits.core.oam.dev is Unknown:
workloaddefinition.core.oam.dev/containerizedworkloads.core.oam.dev is Unknown:
resources failed to the reached Current status
traitdefinition.core.oam.dev/manualscalertraits.core.oam.dev pruned
configmap/grouping-object-a4e18a93 pruned
2 resource(s) pruned
```

It can't recognise some of my CRDs saying `xxx is Unknown` while some other CRDs like `applicationconfiguration.core.oam.dev/` is OK.

Here's the CRD which can't be recognised:

```
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: traitdefinitions.core.oam.dev
spec:
  conversion:
    strategy: None
  group: core.oam.dev
  names:
    kind: TraitDefinition
    listKind: TraitDefinitionList
    plural: traitdefinitions
    singular: traitdefinition
  preserveUnknownFields: true
  scope: Cluster
  versions:
  - additionalPrinterColumns:
    - jsonPath: .spec.definitionRef.name
      name: DEFINITION-NAME
      type: string
    name: v1alpha2
    schema:
      openAPIV3Schema:
        description: A TraitDefinition registers a kind of Kubernetes custom resource
          as a valid OAM trait kind by referencing its CustomResourceDefinition. The
          CRD is used to validate the schema of the trait when it is embedded in an
          OAM ApplicationConfiguration.
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: A TraitDefinitionSpec defines the desired state of a TraitDefinition.
            properties:
              appliesToWorkloads:
                description: AppliesToWorkloads specifies the list of workload kinds
                  this trait applies to. Workload kinds are specified in kind.group/version
                  format, e.g. server.core.oam.dev/v1alpha2. Traits that omit this
                  field apply to all workload kinds.
                items:
                  type: string
                type: array
              definitionRef:
                description: Reference to the CustomResourceDefinition that defines
                  this trait kind.
                properties:
                  name:
                    description: Name of the referenced CustomResourceDefinition.
                    type: string
                required:
                - name
                type: object
            required:
            - definitionRef
            type: object
        type: object
    served: true
    storage: true
    subresources: {}
```

CR:

```
apiVersion: core.oam.dev/v1alpha2
kind: TraitDefinition
metadata:
  name: manualscalertraits.core.oam.dev
spec:
  definitionRef:
    name: manualscalertraits.core.oam.dev
```
