### ISSUE TITLE
[Guides] kpt pkg update is misleading

### ISSUE THREAD

**Issue by gosharplite** [GoogleContainerTools/kpt#524]
```
kpt pkg update helloworld@v0.5.0 --strategy=resource-merge
```
After the above command, the image tag will not change from `0.1.0` to `v0.3.0`.

**Comment by gosharplite** [comment]
I suspect there is a mismatch between tag and commit hash.

**Comment by mortent** [comment]
I think this might be an actual bug. I see that if do
```
kpt pkg get $REPO/package-examples/helloworld-set@v0.3.0 helloworld
kpt pkg update helloworld@v0.5.0 --strategy=resource-merge
```
I end up with the image tag `0.1.0`.

But if I do 
```
kpt pkg get $REPO/package-examples/helloworld-set@v0.5.0 helloworld
```
I do get the expected image tag `0.3.0`

**Comment by gosharplite** [comment]
Yes, it seems a change in comment does not trigger `resource-merge`.

**Comment by phanimarupaka** [comment]
@mortent @gosharplite 

Here are the steps I followed
kpt pkg get $SRC_REPO/package-examples/helloworld-set@v0.3.0 helloworld
deploy.yaml is same as here 
https://github.com/GoogleContainerTools/kpt/blob/package-examples/helloworld-set/v0.3.0/package-examples/helloworld-set/deploy.yaml

kpt pkg update helloworld@v0.5.0 --strategy=resource-merge
deploy.yaml is same as here
https://github.com/GoogleContainerTools/kpt/blob/package-examples/helloworld-set/v0.5.0/package-examples/helloworld-set/deploy.yaml

If you observe there are two types of tags in repo:
v0.3.0 and package-examples/helloworld-set/v0.3.0
v0.5.0 and package-examples/helloworld-set/v0.5.0

That might be leading to this confusion?

**Comment by gosharplite** [comment]
@phanimarupaka @mortent 

Yes, it could be a tag mismatch issue.

At the end, the Kptfile changed to below hash.
```
commit: 3f173ad974081896b47f6929b2c3cb595d71af94
```

The image tag `v0.3.0` is associated this hash. (`subdirectory version@v0.5.0`)
```
https://github.com/GoogleContainerTools/kpt/blob/3f173ad974081896b47f6929b2c3cb595d71af94/package-examples/helloworld-set/deploy.yaml
```

But it seems the image tag `0.1.0` of `repo version@v0.5.0` is used instead.
```
https://github.com/GoogleContainerTools/kpt/blob/v0.5.0/package-examples/helloworld-set/deploy.yaml
```

**Comment by mortent** [comment]
So I agree this might be caused by the different tags. But it seems pretty clear to me that the result we want from running:
```
kpt pkg get $REPO/package-examples/helloworld-set@v0.3.0 helloworld
kpt pkg update helloworld@v0.5.0 --strategy=resource-merge
```
is that my local state should reflect that of the tag `package-examples/helloworld-set/v0.5.0`. And the value of the image tag should be [v0.3.0](https://github.com/GoogleContainerTools/kpt/blob/package-examples/helloworld-set/v0.5.0/package-examples/helloworld-set/deploy.yaml#L34). 

@phanimarupaka Are you getting a different result or do you expect a different result?

**Comment by phanimarupaka** [comment]
@mortent If I run these commands

`kpt pkg get $REPO/package-examples/helloworld-set@v0.3.0 helloworld`
`kpt pkg update helloworld@v0.5.0 --strategy=resource-merge`

My local state reflects this [v0.3.0](https://github.com/GoogleContainerTools/kpt/blob/package-examples/helloworld-set/v0.5.0/package-examples/helloworld-set/deploy.yaml#L34). 

So it is as expected for me. Did you try with the latest kpt release?

**Comment by phanimarupaka** [comment]
@mortent @gosharplite The issue is due to Kptfiles not being merged in a 3 way fashion. If you observe, even Kptfile setter value is not being changed to v0.3.0. I am working on fixing it.

**Comment by gosharplite** [comment]
@phanimarupaka You observation is correct.

After
`kpt pkg update helloworld@v0.5.0 --strategy=resource-merge`

The Kptfile setter value has not been changed  to `v0.3.0`.
```
apiVersion: kpt.dev/v1alpha1
kind: Kptfile
metadata:
    name: hello-world-set
upstream:
    type: git
    git:
        commit: 3f173ad974081896b47f6929b2c3cb595d71af94
        repo: https://github.com/GoogleContainerTools/kpt
        directory: /package-examples/helloworld-set
        ref: v0.5.0
.
.
        io.k8s.cli.setters.image-tag:
            description: hello-world image tag
            x-k8s-cli:
                setter:
                    name: image-tag
                    setBy: package-default
                    value: 0.1.0
```
