### ISSUE TITLE
Move wait logic to standalone command

### ISSUE THREAD

**Issue by seaneagan** [GoogleContainerTools/kpt#525]
Statusing of documents is not only useful at the time of application, but also at any point in the document's lifecycle, so it would be useful to extract the wait logic into its own command. Instead of:

```
kpt live apply --wait-for-reconcile  --wait-timeout=15m --wait-polling-period=5s
```
it would be:
```
kpt live apply DIR 
kpt live wait --timeout=15m --polling-period=5s DIR
...
# run again for debugging purposes etc.
kpt live wait --polling-period=5s DIR
```

When using DIR, it could use the same mechanism as pruning to identify the existing applied document set:

`cli-utils.sigs.k8s.io/inventory-id: test-group`

Related questions for the wait logic:

1. Has using resource watches instead of polling been considered?
2. Doesn't there need to be something to additionally ensure that the e.g. `status.observedGeneration` matches the `metadata.generation`? Relying on only conditions would mean that potentially the status condition won't have been updated yet since the document application.
2. What about allowing metadata on CRDs for when they can't break backward compatibility to match the standard status conditions:

```
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: mycr.example.org
  annotations:
    cli-utils.sigs.k8s.io/reconciling-condition: Succeeded!=true
    cli-utils.sigs.k8s.io/stalled-condition: Failed=true
```
