### ISSUE TITLE
`kpt cfg create-subst` can't parse some string 

### ISSUE THREAD

**Issue by yuwenma** [GoogleContainerTools/kpt#547]
###  Use Case 
add substitution to mark "ns1" as setter "namespace"

#### Expected
run the following command and it adds substitution and refers the substitution in the yaml file.
```bash
kpt cfg create-subst . scoped-namespace "--scoped-namespace=ns1" --pattern "--scoped-namespace=NAMESPACE" --value NAMESPACE=namespace 

```

```yaml
spec:
      containers:
      - args:
        - --scoped-namespace=ns1 
        - --stderrthreshold=INFO
        - --prometheus-scrape-endpoint=:8888
        command:
        - /configconnector/manager
```
####  Actual output:
1. Raises error about unknown flag "--scoped-namespace=ns1"
2. Tried using backslash and empty space at the beginning of the "--scoped-namespace", still couldn't add the reference to the yaml

###  Workaround:
Manually add substitution and reference 
```yaml

    io.k8s.cli.substitutions.scoped-namespace:
      x-k8s-cli:
        substitution:
          name: scoped-namespace
          pattern: --scoped-namespace=NAMESPACE
          values:
          - marker: NAMESPACE
            ref: '#/definitions/io.k8s.cli.setters.namespace'
```
```yaml
      containers:
      - args:
        - --scoped-namespace=ns1 # {"$ref":"#/definitions/io.k8s.cli.substitutions.scoped-namespace"}
        - --stderrthreshold=INFO
        - --prometheus-scrape-endpoint=:8888
        command:
        - /configconnector/manager
```

### Prove the workaround works
```bash
kpt cfg set . namespace ns2
```
The `--scoped-namespace=ns1 ` is changed to `--scoped-namespace=ns2`
