### ISSUE TITLE
Support nested substitutions for better kpt cfg management. 

### ISSUE THREAD

**Issue by yuwenma** [GoogleContainerTools/kpt#551]
Expected behavior:

substitution can use other substitution as their value. 
e.g. 
```yaml
openAPI:
  definitions:
    io.k8s.cli.setters.namespace:
      x-k8s-cli:
        setter:
          name: namespace
          value: ns1
    io.k8s.cli.substitutions.sa:
      x-k8s-cli:
        substitution:
          name: sa
          pattern: service-account-NAMESPACE
          values:
          - marker: NAMESPACE
            ref: '#/definitions/io.k8s.cli.setters.namespace'
    io.k8s.cli.substitutions.member1:
      x-k8s-cli:
        substitution:
          name: sa
          pattern: service-account-NAMESPACE@member1.gcloudserviceaccount.com
          values:
          - marker: NAMESPACE
            ref: '#/definitions/io.k8s.cli.setters.namespace'
  
    io.k8s.cli.substitutions.member2:
      x-k8s-cli:
        substitution:
          name: sa
          pattern: service-account-NAMESPACE@member2.gcloudserviceaccount.com
          values:
          - marker: NAMESPACE
            ref: '#/definitions/io.k8s.cli.setters.namespace'
```

In the above example, it is more meaningful if substitutions `member1` and `member2` can accept the substitution `namespace` as their value.
Besides, if some part of the pattern (like the SA in the example) can be treated as a whole, it's easier to manage/update if the value of SA changes (like a const var).
