### ISSUE TITLE
Make parent field context usable in setter

### ISSUE THREAD

**Issue by trodge** [GoogleContainerTools/kpt#575]
When creating setters, it is currently only possible to match on the field name, sometimes this is not ideal when the field that will be set has a generic name but its parent name is more unique, for example, in the project resource:

```
spec:
  name: KCC Solutions Sample
  billingAccountRef:
    external: ''
```

It would be nice to be able to use

`kpt cfg create-setter project-factory/core/ billing_account '' --type "string" --field "billingAccountRef.external" --description "The ID of the billing account to associate this project with"
`
To only match fields with the name "external" that have parent "billingAccountRef"
