### ISSUE TITLE
apply guide does not work

### ISSUE THREAD

**Issue by cflewis** [GoogleContainerTools/kpt#665]
Version: v0.24.0 (internal Google build).

https://googlecontainertools.github.io/kpt/guides/consumer/apply/ asks the user to perform these steps:

```
export SRC_REPO=https://github.com/GoogleContainerTools/kpt.git
kpt pkg get $SRC_REPO/package-examples/helloworld-set@v0.3.0 helloworld
kpt live init helloworld
kpt live apply helloworld --wait-for-reconcile
```

This does not do what it thinks it should do, as the image it tries to pull is _not_ v0.3.0. The deploy file uses this:

```
    spec:
      containers:
      - name: helloworld-gke
        image: gcr.io/kpt-dev/helloworld-gke:0.1.0 # {"$ref":"#/definitions/io.k8s.cli.substitutions.image-tag"}
```

Not only is this not v0.3.0, 0.1.0 doesn't exist (it's v0.1.0) so the tutorial fails :(
