### ISSUE TITLE
`kpt cfg set` cannot update namespace

### ISSUE THREAD

**Issue by jstrachan** [GoogleContainerTools/kpt#683]
I'd like to be able to set the namespace of all resources after running a `kpt pkg get ...` command.

FWIW the background is if using [Config Sync with unstructured layout](https://cloud.google.com/anthos-config-management/docs/how-to/unstructured-repo) so that apps in a namespace can be fetched via `kpt pkg get` into separate folders; each resource needs an explicit namespace.

I tried creating setters via both of these:

```
$ kpt cfg create-setter mydir namespace myns --field "namespace"
$ kpt cfg create-setter mydir namespace myns --field "metadata.namespace"
```
in either case when I try set a value I get 0 fields updated:

```
$ kpt cfg set mydir namespace something
set 0 fields
```

Is there a trick to set namespaces; or is this a limitation of the underlying kustomize setter logic?

**Comment by phanimarupaka** [comment]
@jstrachan Can you point me to the exact command you used here so that I can reproduce with the resource files. `kpt pkg get ...`

**Comment by jstrachan** [comment]
sure, these commands should reproduce the issue for you (sorry, I should have included them!)

```bash
$ kpt pkg get https://github.com/jstrachan/nodey460.git/kubernetes/nodey460/templates@v1.0.12 nodey460/
fetching package /kubernetes/nodey460/templates from https://github.com/jstrachan/nodey460 to nodey460

$ kpt cfg create-setter nodey460 namespace myapps --field "metadata.namespace"

$ kpt cfg set nodey460 namespace cheese 
set 0 fields
```
on completion the `Kptfile` is updated with the new value but the resource YAML files remain unchanged.

```yaml
# demo460/Kptfile
apiVersion: kpt.dev/v1alpha1
kind: Kptfile
metadata:
  name: nodey460
upstream:
  type: git
  git:
    commit: 8885116aaff2740901969b7b797b021e00c35bef
    repo: https://github.com/jstrachan/nodey460
    directory: /kubernetes/nodey460/templates
    ref: v1.0.12
openAPI:
  definitions:
    io.k8s.cli.setters.namespace:
      x-k8s-cli:
        setter:
          name: namespace
          value: cheese
```

I tried using the latest release and master build of `kpt` and got the same thing. Also got the same using `--field "namespace"`.

I tried debugging and didn't see anything obvious, it seemed to invoke kustomize and I didn't spot any errors. (I don't know kustomize well enough yet to grok where things went wrong).
