### ISSUE TITLE
kpt fn run corrupts long lines with trailing comment

### ISSUE THREAD

**Issue by yhrn** [GoogleContainerTools/kpt#685]
kpt v0.27.0

To reproduce execute:

```shell
kpt fn run --image gcr.io/kpt-functions/no-op <<EOF
apiVersion: v1
kind: ConfigMap
metadata:
  name: test
data:
  somekey: '012345678901234567890123456789012345678901234567890123456789012345678901234' # x
EOF
```
The output will be

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: test
  annotations:
    config.kubernetes.io/path: 'configmap_test.yaml'
data:
  somekey: >-
    012345678901234567890123456789012345678901234567890123456789012345678901234# x
```
As you can see the white space before the comment has now become part of the value. If the value is one character shorter the output is not corrupted.
