### ISSUE TITLE
create-setter ignores array type in Kptfile

### ISSUE THREAD

**Issue by shawnzhu** [GoogleContainerTools/kpt#698]
```
$ kpt version
0.27.0
```

## Problem
Given:
```YAML
# input.yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: ml-pipeline-tensorboard-ui
spec:
  gateways:
  - "kubeflow-gateway"
  hosts:
  - '*'
```
And `Kptfile`:

```YAML
kind: Kptfile
openAPI:
  definitions: {}
```

Run:
```
$ kpt cfg create-setter tmp/ \
  istio-gateway "kubeflow-gateway" \
  --type array --field "spec.gateways"
$ kpt cfg list-setters tmp/
Error: The input value doesn't validate against provided OpenAPI schema: validation failure list:
istio-gateway in body must be of type array: "string"
```

While the expected output is:

```
$ kpt cfg list-setters tmp/
      NAME                       VALUE                  SET BY            DESCRIPTION             COUNT                                  
  istiogateway    [istio-system/istio-ingressgateway]                                             2
```

## Diagnose

When checking `Kptfile`, I've noticed that it uses `value` instead of `listValues` under `setter`:

```YAML
# Kptfile
kind: Kptfile
openAPI:
  definitions: {io.k8s.cli.setters.istio-gateway: {type: array, x-k8s-cli: {setter: {
          name: istio-gateway, value: kubeflow-gateway}}}}
```

While the expected `Kptfile` should be:

```YAML
openAPI:
  definitions:
    io.k8s.cli.setters.istiogateway:
      type: array
      x-k8s-cli:
        setter:
          name: istiogateway
          listValues:
          - "istio-system/istio-ingressgateway"
```

According to https://googlecontainertools.github.io/kpt/guides/producer/setters/#setting-lists

> Note: Move the setter reference from the element (`- "a"`) to the list (`list:` )

another problem is the field reference in updated `input.yaml` is not in the expected line (should be at the line of `gateways:`):

Actual result:
```YAML
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: ml-pipeline-tensorboard-ui
spec:
  gateways:
  - "kubeflow-gateway" # {"$ref":"#/definitions/io.k8s.cli.setters.istio-gateway"}
  hosts:
  - '*'
```

**Comment by shawnzhu** [comment]
Discovered when trying to using kpt setter in https://github.com/kubeflow/manifests/pull/1211

**Comment by phanimarupaka** [comment]
@shawnzhu As mentioned [here]( https://googlecontainertools.github.io/kpt/guides/producer/setters/#setting-lists) you should move the reference to the list key and it works fine.

`kpt cfg create-setter /tmp istio-gateway "kubeflow-gateway" --type array --field "spec.gateways"`

Move the reference and the input.yaml. This is a manual step currently for creating setter for list-item
```YAML
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: ml-pipeline-tensorboard-ui
spec:
  gateways: # {"$kpt-set":"istio-gateway"}
  - "kubeflow-gateway"
  hosts:
  - '*'
```

And list-setters works fine

```kpt cfg list-setters /tmp
     NAME             VALUE         SET BY   DESCRIPTION   COUNT  
 istio-gateway   kubeflow-gateway                          0   
```
