### ISSUE TITLE
String type setter is not allowed to be numbers

### ISSUE THREAD

**Issue by cydu-cloud** [GoogleContainerTools/kpt#713]
Sometimes my string just happen to be "numbers", but kpt will compain about it. 

Kptfile:

```yaml
apiVersion: kpt.dev/v1alpha1
kind: Kptfile
metadata:
  name: str-val
packageMetadata:
  shortDescription: sample description
openAPI:
  definitions:
    io.k8s.cli.setters.stringValue:
      type: string
      x-k8s-cli:
        setter:
          name: stringValue
          value: '1234'
    io.k8s.cli.substitutions.subValue:
      type: string
      x-k8s-cli:
        substitution:
          name: subValue
          pattern: "prefix-VALUE"
          values:
          - marker: VALUE
            ref: '#/definitions/io.k8s.cli.setters.stringValue'
```

config.yaml
```yaml
apiVersion: test/alpha
kind: strValue
metadata:
  name: strValue
spec:
  stringVal: 1234 # {"$ref":"#/definitions/io.k8s.cli.setters.stringValue"}
  subVal: prefix-1234 # {"$ref":"#/definitions/io.k8s.cli.substitutions.subValue"}
```

Error: 

```bash
> ~/bin/kpt cfg list-setters .
Error: The input value doesn't validate against provided OpenAPI schema: validation failure list:
stringValue in body must be of type string: "number"
> ~/bin/kpt version
v0.29.0
```
Expectation: 

"1234" should be a valid string although it's also a number.
