### ISSUE TITLE
Can't use nested substitute on cockroach example. 

### ISSUE THREAD

**Issue by yuwenma** [GoogleContainerTools/kpt#729]
#### step 1 add a test field
To test the nested substitution, I added a new field in the [cockroachdb-statefulset.yaml](https://github.com/kubernetes/examples/blob/master/staging/cockroachdb/cockroachdb-statefulset.yaml) between line6-7
```yaml
  name: cockroachdb-public
  namespace: /cockroach/cockroach-data/cluster_exists_marker
    app: cockroachdb # {"$ref":"#/definitions/io.k8s.cli.setters.app_name"}
```

#### step 2 Check KptFile before running test
After successfully created some setters and substitutions, my kptFile is like this 
```yaml
apiVersion: kpt.dev/v1alpha1
kind: Kptfile
metadata:
  name: cockroachdb
upstream:
  type: git
  git:
    commit: 6f9fad9e3df6a439becde6985c20e6f18554a78e
    repo: https://github.com/kubernetes/examples
    directory: /staging/cockroachdb
    ref: master
openAPI:
  definitions:
    io.k8s.cli.setters.app_name:
      x-k8s-cli:
        setter:
          name: app_name
          value: cockroachdb
    io.k8s.cli.setters.path:
      x-k8s-cli:
        setter:
          name: path
          value: cockroach-data
    io.k8s.cli.substitutions.mount_path:
      x-k8s-cli:
        substitution:
          name: mount_path
          pattern: /${app_name}/${path}
          values:
          - marker: ${app_name}
            ref: '#/definitions/io.k8s.cli.setters.app_name'
          - marker: ${path}
            ref: '#/definitions/io.k8s.cli.setters.path'
    io.k8s.cli.setters.marker:
      x-k8s-cli:
        setter:
          name: marker
          value: cluster_exists_marker
``` 

### Test
Now I want to create a nested substitution fake_ns for the "namespace" field I added to the first setup, which is of the form ${mount_path}/${marker}, where mount_path is a *subst* and marker is a *setter*

Run
```bash 
kpt cfg create-subst . fake_ns  --field-value "/cockroach/cockroach-data/cluster_exists_marker"  --pattern "\${mount_path}/\${marker}"
```

The updated kptfile does create a substitute, but not using the subst mount_path but creating a setter of the same name *mount_path*

Here the file kptfile after running the command

```yaml
apiVersion: kpt.dev/v1alpha1
kind: Kptfile
metadata:
  name: cockroachdb
upstream:
  type: git
  git:
    commit: 6f9fad9e3df6a439becde6985c20e6f18554a78e
    repo: https://github.com/kubernetes/examples
    directory: /staging/cockroachdb
    ref: master
openAPI:
  definitions:
    io.k8s.cli.setters.app_name:
      x-k8s-cli:
        setter:
          name: app_name
          value: cockroachdb
    io.k8s.cli.setters.path:
      x-k8s-cli:
        setter:
          name: path
          value: cockroach-data
    io.k8s.cli.substitutions.mount_path:
      x-k8s-cli:
        substitution:
          name: mount_path
          pattern: /${app_name}/${path}
          values:
          - marker: ${app_name}
            ref: '#/definitions/io.k8s.cli.setters.app_name'
          - marker: ${path}
            ref: '#/definitions/io.k8s.cli.setters.path'
    io.k8s.cli.setters.marker:
      x-k8s-cli:
        setter:
          name: marker
          value: cluster_exists_marker
    io.k8s.cli.setters.mount_path:
      x-k8s-cli:
        setter:
          name: mount_path
          value: ""
    io.k8s.cli.substitutions.fake_ns:
      x-k8s-cli:
        substitution:
          name: fake_ns
          pattern: ${mount_path}/${marker}
          values:
          - marker: ${mount_path}
            ref: '#/definitions/io.k8s.cli.setters.mount_path'
          - marker: ${marker}
            ref: '#/definitions/io.k8s.cli.setters.marker'
```

**Comment by yuwenma** [comment]
The .yaml file is successfully updated.
```yaml

  name: cockroachdb-public
  namespace: /cockroach/cockroach-data/cluster_exists_marker # {"$ref":"#/definitions/io.k8s.cli.substitutions.fake_ns"}
  labels:
    app: cockroachdb # {"$ref":"#/definitions/io.k8s.cli.setters.app_name"}
```
