### ISSUE TITLE
Comment preservation logic has issue with inline comments

### ISSUE THREAD

**Issue by frankfarzan** [GoogleContainerTools/kpt#766]
Context: https://github.com/GoogleContainerTools/kpt/issues/685

Can repo with this:

1. File on disk:

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: test
data:
  somekey: '012345678901234567890123456789012345678901234567890123456789012345678901234' # x
```

2. Output of a function:

```
...
apiVersion: v1
kind: ConfigMap
metadata:
  name: test
  annotations:
    config.kubernetes.io/path: 'configmap_test.yaml'
data:
  somekey: >-
    012345678901234567890123456789012345678901234567890123456789012345678901234
```

Note the following:
- A function MAY remove comments from YAML. This is a valid transformation allowed by the spec.
- A function MAY format YAML (in this case split a line into 2). This is a valid transformation allowed by the spec.

3. Output of 'kpt fn sink'

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: test
  annotations:
    config.kubernetes.io/path: 'configmap_test.yaml'
data:
  somekey: >-
    012345678901234567890123456789012345678901234567890123456789012345678901234# x
```

Note the following:
- 'kpt fn sink' tries to preserve comments by diffing 1 and 2. In this case, it's incorrectly appending `#x` without a space.
