### ISSUE TITLE
create-subst should provide support for wildcard matches in substitutions

### ISSUE THREAD

**Issue by wstrange** [GoogleContainerTools/kpt#772]
It woud be nice if substitutions can match wild card patterns. For example, consider a value in a configmap:

```
data:
   FQDN: acme.com
   MY_FOO_URL: https://acme.com/foo
   MY_BAR_URL:  https://acme.com/bar
```

I'd like to have a single setter `fqdn` that sets the FQDN, including the fqdn embedded in the URLS:

```
kpt cfg set DIR/ fqdn mydomain.com
```

Currently the `--pattern` does not allow wildcard matches like `https://\${fqdn}/*`

The command to create the substitution would be something like:
```
 kpt cfg create-subst DIR/ fqdnurl --field-value https://default.iam.example.com/* --pattern https://\${fqdn}/*
```

See also: https://kubernetes.slack.com/archives/C0155NSPJSZ/p1593460379024400
