### ISSUE TITLE
fix(fn.kustomize.build): provide git binary for remote ressources execution

### ISSUE THREAD

**Issue by davinkevin** [GoogleContainerTools/kpt#791]
Hi, 

I try to use the `kustomize-build' function to create my source, the problem is I use, for simplicity a remote `bases`/`resources` and the image containing the node+kustomize doesn't contain the git binary required by `kustomize` for fetching the assets.

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: podcast-server-example

resources:
- git::https://gitlab.com/davinkevin/Podcast-Server.git//deployment/kubernetes/base/

configMapGenerator:
- name: podcast-server
  behavior: merge
  literals:
  - "max-update-parallels=15" # {"$ref":"#/definitions/io.k8s.cli.substitutions.max-update-parallels"}
  - "concurrent-download=126" # {"$ref":"#/definitions/io.k8s.cli.substitutions.concurrent-download"}
  - "number-of-day-to-download=31" # {"$ref":"#/definitions/io.k8s.cli.substitutions.number-of-day-to-download"}
  - "number-of-day-to-save-cover=128" # {"$ref":"#/definitions/io.k8s.cli.substitutions.number-of-day-to-save-cover"}

secretGenerator:
- name: podcast-server
  behavior: merge
  literals:
  - database.password=bar
```

The result is: 

```log
apiVersion: v1
kind: ResourceList
metadata:
  name: output
items: []
results:
- message: |
    Kustomize build command results in error: Error: accumulating resources: accumulateFile "accumulating resources from 'git::https://gitlab.com/davinkevin/Podcast-Server.git//deployment/kubernetes/base/': evalsymlink failure on '/source/podcast-server/git::https:/gitlab.com/davinkevin/Podcast-Server.git/deployment/kubernetes/base' : lstat /source/podcast-server/git::https:: no such file or directory", loader.New "no 'git' program on path: exec: \"git\": executable file not found in $PATH"
  severity: error
```

I will do a PR to add git in the image BTW

**Comment by prachirp** [comment]
Thanks for the fix @davinkevin ! I pushed the new image to gcr.io/kpt-functions/kustomize-build and will add a test so there's no regression. Please close this out after you verify the new image.

**Comment by davinkevin** [comment]
Thanks you to for the integration ❤️

I've tested it like you do in the `e2e.sh` and this is working perfectly.

But, I tried to run it through `kpt` with the imperative or declarative way and I end up with the no ouptut or error. Could you provide and example on how to run it in both situation?

If I run it imperatively, I have the following response:
![image](https://user-images.githubusercontent.com/1970922/86884986-bdf93300-c0f4-11ea-8756-4fb56ec960f1.png)

If I run it declaratively, with the following function definition:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-config
  annotations:
    config.kubernetes.io/local-config: "true"
    config.k8s.io/function: |
      container:
        image:  gcr.io/kpt-functions/kustomize-build
        network:
          required: true
data:
  path: /source
```

I have the following result
![image](https://user-images.githubusercontent.com/1970922/86885347-67402900-c0f5-11ea-99b1-6b69a224b059.png)

I've tried a lot of solution, but in fact, I didn't found (or miss) the information about where are mounted the file system inside the docker container when using `kpt`. Due to this, I can't provide kustomize the correct build path. Could you help me on this ?
