### ISSUE TITLE
create-setter bug with dots in setter name

### ISSUE THREAD

**Issue by marklester** [GoogleContainerTools/kpt#808]
kpt version:  0.31.0

```
kpt cfg create-setter app/ http.port 9283
```
kptFile:
```
...
    io.k8s.cli.setters.http.port:
      x-k8s-cli:
        setter:
          name: http.port
          value: "9283"
          isSet: true
```
deployment.yaml
```
...
        ports:
        - name: web
          containerPort: 9283 # {"$kpt-set":"port"}
          protocol: TCP
```

looks like it drops the first part of the name? and I didn't see a valid character section for setter names
