### ISSUE TITLE
Creating setters through substitutions are not adding openapi refs to resoures

### ISSUE THREAD

**Issue by mortent** [GoogleContainerTools/kpt#813]
It is possible to create a substitution that references one or more setters that doesn't exist. This will create the setter in the Kptfile, but it doesn't actually add the references to the setter in the manifests.

Starting with a package without any setters or substitutions.

Kptfile:
```
apiVersion: kpt.dev/v1alpha1
kind: Kptfile
metadata:
  name: pkg
packageMetadata:
  shortDescription: sample description
```
Manifest:
```
apiVersion: test/alpha
kind: strValue
metadata:
  name: strValue
spec:
  stringVal: 1234
  subVal: prefix-1234
```

Then add a substitution with the following command:
```
kpt cfg create-subst . foo --field-value=prefix-1234 --pattern prefix-\${foobar}
```

The resulting files will be the following
Kptfile:
```
apiVersion: kpt.dev/v1alpha1
kind: Kptfile
metadata:
  name: pkg
packageMetadata:
  shortDescription: sample description
openAPI:
  definitions:
    io.k8s.cli.substitutions.foo:
      x-k8s-cli:
        substitution:
          name: foo
          pattern: prefix-${foobar}
          values:
          - marker: ${foobar}
            ref: '#/definitions/io.k8s.cli.setters.foobar'
    io.k8s.cli.setters.foobar:
      x-k8s-cli:
        setter:
          name: foobar
          value: "1234"
```
Manifest:
```
apiVersion: test/alpha
kind: strValue
metadata:
  name: strValue
spec:
  stringVal: 1234
  subVal: prefix-1234 # {"$kpt-set":"foo"}
```

The created setter actually matches the `spec.stringVal` field, but no openapi reference is added.
