### ISSUE TITLE
TS SDK test runner does not handle structured results in output

### ISSUE THREAD

**Issue by prachirp** [GoogleContainerTools/kpt#817]
For example, the following unit test fails:

```
describe('helmTemplate', () => {
  it('outputs helm template error result given undefined function config', async () => {
    const input = new Configs(undefined, undefined);
    const helmError = "Helm template command results in error: Error: \"helm template\" requires at\nleast 1 argument\n\n\nUsage:  helm template [NAME] [CHART] [flags]";
    const errorResult:Result = {
      severity: 'error',
      message: helmError,
    };
    const output = new Configs(undefined);
    output.addResults(errorResult);

    await RUNNER.assert(
      input,
      output
    );
  });
});
```
with an error about yaml multi-line strings (https://yaml-multiline.info/)
```
    Expected 'apiVersion: v1
    items: []
    kind: ResourceList
    metadata:
      name: output
    results:
    - message: >
        Helm template command results in error: Error: "helm template" requires at
        least 1 argument
    
    
        Usage:  helm template [NAME] [CHART] [flags]
      severity: error
    ' to equal 'apiVersion: v1
    items: []
    kind: ResourceList
    metadata:
      name: output
    results:
    - message: |-
        Helm template command results in error: Error: "helm template" requires at
        least 1 argument
    
    
        Usage:  helm template [NAME] [CHART] [flags]
      severity: error
    '.
```
