### ISSUE TITLE
Sourcing a ResourceList file should return the ResourceList itself

### ISSUE THREAD

**Issue by ZhuGongpu** [GoogleContainerTools/kpt#833]
Consider you have a `deployment.yaml` file:
```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: development
```
Running `kpt fn source deployment.yaml | kpt fn source` will get:
```yaml
apiVersion: config.kubernetes.io/v1alpha1
kind: ResourceList
items:
- apiVersion: v1
  kind: Namespace
  metadata:
    name: development
    annotations:
      config.kubernetes.io/index: '0'
      config.kubernetes.io/path: 'deployment.yaml'
```
However, if we save the output of the first `kpt fn source` into file and then run `kpt fn source` again, e.g.
```bash
kpt fn source deployment.yaml > temp.yaml
kpt fn source temp.yaml
```
will get:
```yaml
apiVersion: config.kubernetes.io/v1alpha1
kind: ResourceList
items:
- apiVersion: config.kubernetes.io/v1alpha1
  kind: ResourceList
  items:
  - apiVersion: v1
    kind: Namespace
    metadata:
      name: development
      annotations:
        config.kubernetes.io/index: '0'
        config.kubernetes.io/path: 'deployment.yaml'
  metadata:
    annotations:
      config.kubernetes.io/index: '0'
      config.kubernetes.io/path: 'temp.yaml'
```

Is this an inconsistent behavior? @mortent @frankfarzan
