### ISSUE TITLE
Kpt 0.30.1 breaks cfg supporting int type

### ISSUE THREAD

**Issue by elfinhe** [GoogleContainerTools/kpt#845]
we had a kpt setter using int type, which was created by old version kpt:

```
 io.k8s.cli.setters.gcloud.container.nodepool.max-nodes:
      type: int
      x-k8s-cli:
        setter:
          name: gcloud.container.nodepool.max-nodes
          value: "4"
```

which is referenced by a yaml

```
spec:
  autoscaling:
    maxNodeCount: 4 # {"$ref":"#/definitions/io.k8s.cli.setters.gcloud.container.nodepool.max-nodes"}
```

KPT version:
```
$ kpt version
v0.30.1
```

When we run `kpt cfg list-setters my-folder/`, we get this validation error:

```
$ kpt cfg list-setters my-folder/
Error: The input value doesn't validate against provided OpenAPI schema: validation failure list:
gcloud.container.nodepool.max-nodes in body must be of type int: "integer"
```

We've tried multiple ways to tweak the configs but still cannot specify int type in the Kptfile.

Question - what the right way to set int type setters in the kpt 0.30.1? Is this a bug or the type is not supported any more.
