### ISSUE TITLE
kpt fn source loses complete information of file paths

### ISSUE THREAD

**Issue by ZhuGongpu** [GoogleContainerTools/kpt#882]
```shell script
mkdir kpt-fn-source-test
cd kpt-fn-source-test
kpt pkg get https://github.com/kubernetes-sigs/kustomize/functions/examples/injection-tshirt-sizes injection-tshirt-sizes
kpt pkg get https://github.com/kubernetes-sigs/kustomize/functions/examples/application-cr application-cr
```
Running this command will get a `kpt-fn-source-test` directory with two packages:

```
.
├── application-cr
│   ├── config
│   │   └── fn-config.yaml
│   └── local-resource
│       └── example.yaml
└── injection-tshirt-sizes
    └── local-resource
        └── example-use.yaml
```

Then running the following command:

```shell script
kpt fn source application-cr injection-tshirt-sizes | kpt fn sink result
```

will produce a `result` directory like this:

```
.
├── config
│   └── fn-config.yaml
└── local-resource
    ├── example-use.yaml
    └── example.yaml
```

The `result` directory should be identical to the `kpt-fn-source-test` diectory. But `application-cr` and `injection-tshirt-sizes` directories at the root level are missing. 

This is because `kpt fn source DIRs` will only retain relative paths to DIRs:

```yaml
apiVersion: config.kubernetes.io/v1alpha1
kind: ResourceList
items:
- apiVersion: examples.config.kubernetes.io/v1beta1
  kind: CreateApp
  metadata:
    annotations:
      config.kubernetes.io/function: |
        container:
          image: gcr.io/kustomize-functions/create-application:v0.1.0
      config.kubernetes.io/index: '0'
      # NOTE: it should be 'application-cr/config/fn-config.yaml'
      config.kubernetes.io/path: 'config/fn-config.yaml'
  ...
```

In this case, the expected `config.kubernetes.io/path` above should be `application-cr/config/fn-config.yaml`.

**Comment by mikebz** [comment]
@runewake2 can you take a look?

**Comment by runewake2** [comment]
Thanks for the detailed reproduction case. This made it a lot easier to reproduce this.

To get the behavior you are expecting you should be able to run this in the directory that contains your `application-cr` and `injection-tshirt-sizes` directories, in this case the current directory, instead of providing each subdirectory by name. For example:

```sh
kpt fn source . | kpt fn sink result
```

A complete example might look like this:

```sh
➜ mkdir test-sink
➜ cd test-sink
➜ kpt pkg get https://github.com/kubernetes-sigs/kustomize/functions/examples/injection-tshirt-sizes injection-tshirt-sizes
fetching package functions/examples/injection-tshirt-sizes from https://github.com/kubernetes-sigs/kustomize to injection-tshirt-sizes
➜ kpt pkg get https://github.com/kubernetes-sigs/kustomize/functions/examples/application-cr application-cr
fetching package functions/examples/application-cr from https://github.com/kubernetes-sigs/kustomize to application-cr
➜ ls
application-cr         injection-tshirt-sizes
➜ mkdir ../tmp-out
➜ kpt fn source . | kpt fn sink ../tmp-out
➜ ls ../tmp-out
application-cr         injection-tshirt-sizes
```

The `config.kubernetes.io/path` should match what your expecting when used like this as well:

```yml
...
    annotations:
      tshirt-size: small # this injects the resource reservations
      config.kubernetes.io/index: '1'
      config.kubernetes.io/path: 'injection-tshirt-sizes/local-resource/example-use.yaml'
...
```

I'm going to close this issue. If this doesn't address the behavior your seeing or the option I've posted above does not solve your problem then please reopen this issue and I can take another look.
