### ISSUE TITLE
`create-setter` exits with code 0 without creating a setter

### ISSUE THREAD

**Issue by frankfarzan** [GoogleContainerTools/kpt#900]
$ kpt cfg create-setter . project-id --description "GCP Project ID" --required
$ echo $?
$ cat Kptfile 
```
apiVersion: kpt.dev/v1alpha1
kind: Kptfile
metadata:
  name: cicd_gitlab
packageMetadata:
  shortDescription: Deploys GitLab on GCP
openAPI:
  definitions:
    io.k8s.cli.setters.namespace:
      x-k8s-cli:
        setter:
          name: namespace
          value: gitlab-2
          required: true
          isSet: true
      description: Namespace for GitLab deployment
```
