### ISSUE TITLE
create-setter/subst doesn't add openAPI definitions if the section is empty

### ISSUE THREAD

**Issue by phanimarupaka** [GoogleContainerTools/kpt#966]
If if Kptfile has empty openAPI definitions as below, it doesn't create setter/subst definitions. This should be fixed.

```
apiVersion: kpt.dev/v1alpha1
kind: Kptfile
metadata:
  name: Anthos Self Service for Config Management
openAPI:
  definitions:
```
