### ISSUE TITLE
Preserve YAML multiline strings

### ISSUE THREAD

**Issue by kaoet** [GoogleContainerTools/kpt#979]
**What're the files like:**
My `Kptfile`:
```yaml
openAPI:
  definitions:
    io.k8s.cli.setters.v1:
      x-k8s-cli:
        setter:
          name: v1
          value: my-value1
    io.k8s.cli.substitutions.values.yaml:
      x-k8s-cli:
        substitution:
          name: values.yaml
          pattern: |-
            k1: ${v1}
            k2: v2
            k3: v3
          values:
          - marker: ${v1}
            ref: '#/definitions/io.k8s.cli.setters.v1'
```

My `config.yaml`:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-config
data:
  values.yaml: "" # {"$kpt-set": "values.yaml"}
```

**What do I do:**
`kpt cfg set . v1 my-value2`

**What's I actual see:**
My new `config.yaml`:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-config
data:
  values.yaml: "k1: my-value2\nk2: v2\nk3: v3" # {"$kpt-set": "values.yaml"}
```

**What's expected:**
My new `config.yaml`:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-config
data:
  values.yaml: |- # {"$kpt-set": "values.yaml"}
    k1: my-value2
    k2: v2
    k3: v3
```

**Notes:**
1. If at the beginning, I write my `config.yaml` like
```yaml
values.yaml: |- #{"$kpt-set": "values.yaml"}
  k1: my-value1
  k2: v2
  k3: v3
```
Then kpt is unable to find the comment and refuses to update the YAML for me.
2. It's OK for me to add some other options like `# {"$kpt-set": "values.yaml", "multiline": true}` to achieve that result.
